"use client";
import { useEffect,useState } from "react";
const steps=[
  {title:"1 · เตรียมข้อความ",body:"เปิดหน้า สรุปชาร์จ แล้ววาง Order Sheet ตรวจว่าข้อมูลที่ต้องใช้ครบก่อนเริ่ม",panel:"ORDER SHEET",lines:["ข้อมูลตัวอย่างสำหรับสอนใช้","วันรับไว้รักษา: 01/09/2569","วันจำหน่าย: 05/09/2569","บันทึกการรักษาและแผนติดตาม…"],action:"สร้างสรุป"},
  {title:"2 · รอผลจากระบบ",body:"เมื่อกดสร้างสรุป ให้รอสถานะเสร็จ ไม่ต้องกดปุ่มซ้ำ",panel:"กำลังสร้างสรุป…",lines:["อ่านข้อมูลจากบันทึก","จัดหัวข้อตามรูปแบบที่เลือก","ตรวจข้อมูลที่ยังขาด"],action:"กำลังประมวลผล"},
  {title:"3 · ตรวจทานก่อนใช้",body:"อ่านผล ตรวจวันที่และ diagnosis ให้ตรงบันทึก แก้ไขข้อมูลที่จำเป็นก่อนคัดลอก",panel:"ร่างสรุปสำหรับตรวจทาน",lines:["Admit: 01/09/2569","Discharge: 05/09/2569","Diagnosis · ตรวจเทียบกับหลักฐาน","Treatment / Follow-up · ตรวจความครบถ้วน"],action:"ตรวจแล้วคัดลอก"},
  {title:"4 · ถ้าใช้ Auto กับ HOSxP",body:"ตั้งค่าเครื่องและทดสอบก่อนเริ่มจริง พัก/ทำต่อด้วย F9 หยุดด้วย F10 แล้วตรวจผู้ป่วยและข้อมูลก่อนเริ่มใหม่",panel:"DischargeX Auto",lines:["ตั้งค่าเครื่อง → ทดสอบช่วงงาน → เริ่ม","เห็นขั้นตอนปัจจุบันตลอดการทำงาน","พัก / ทำต่อ (F9)","หยุด (F10)"],action:"เริ่มจากการตั้งค่าเครื่อง"},
];
export function GuidePlayer(){const [step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!playing)return;const id=setInterval(()=>setStep(i=>(i+1)%steps.length),6000);return()=>clearInterval(id);},[playing]);
 const s=steps[step];return <div className="overflow-hidden rounded-xl border border-slate-600 bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-700 p-4"><span className="text-sm text-cyan-200">ภาพอธิบายขั้นตอน · ข้อมูลสังเคราะห์ · ไม่มีการเรียก AI หรือควบคุม HOSxP</span><button onClick={()=>setPlaying(v=>!v)} className="rounded bg-cyan-300 px-4 py-2 font-semibold text-slate-950">{playing?"พักภาพ":"เล่นภาพแนะนำ"}</button></div><div className="grid gap-8 p-6 md:grid-cols-2 md:p-10"><div><p className="text-sm text-slate-400">ขั้น {step+1} จาก 4</p><h2 className="mt-4 text-2xl font-semibold">{s.title}</h2><p className="mt-5 text-lg leading-relaxed text-slate-300">{s.body}</p></div><div className="min-h-64 rounded-md border border-cyan-300/25 bg-[#07101d] p-5"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><span className={step===1?"h-4 w-4 animate-spin rounded-full border-2 border-cyan-300 border-t-transparent motion-reduce:animate-none":"h-2 w-2 rounded-full bg-cyan-300"}/><strong>{s.panel}</strong></div><div className="my-5 space-y-4 text-sm text-slate-300">{s.lines.map(l=><p key={l}>{l}</p>)}</div><div className="inline-block rounded bg-cyan-300/15 px-4 py-2 text-sm text-cyan-200">{s.action}</div></div></div><div className="flex flex-wrap gap-2 border-t border-slate-700 p-4">{steps.map((s,i)=><button aria-pressed={step===i} key={s.title} onClick={()=>{setStep(i);setPlaying(false);}} className={"rounded px-4 py-2 text-sm "+(step===i?"bg-slate-200 text-slate-950":"bg-slate-800 text-slate-200")}>{s.title}</button>)}</div></div>;
}
