import type { Metadata } from "next";
import Link from "next/link";
import { ImpactStats } from "./components/ImpactStats";
import { ValueCalculator } from "./components/ValueCalculator";
export const metadata: Metadata = {
  title: { absolute: "DischargeX — ผู้ช่วยสรุปชาร์จ พร้อม Auto สำหรับ HOSxP" },
  description: "เปลี่ยน Doctor Order Sheet เป็นร่างสรุปที่อ่านและตรวจทานง่าย ลองตัวอย่างก่อนสมัคร ใช้บัญชีเดียวกับโปรแกรม Auto สำหรับ HOSxP",
  alternates: { canonical: "/" },
  openGraph: { title: "DischargeX — งานสรุปชาร์จ เริ่มง่ายขึ้น", description: "ลองดูขั้นตอนและผลตัวอย่าง แล้วเริ่มสรุปเคสของคุณ", url:"https://dischargex.net",locale:"th_TH",type:"website" },
};
const primary="inline-flex items-center justify-center rounded-lg bg-cyan-300 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-cyan-300";
export default function Home(){
  return <main className="min-h-screen bg-[#081120] text-slate-100">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"DischargeX",url:"https://dischargex.net",applicationCategory:"HealthApplication",operatingSystem:"Web, Windows",description:"ผู้ช่วยสร้างร่างสรุปชาร์จและกรอก HOSxP โดยมีผู้ใช้ตรวจทาน"})}}/>
    <section className="border-b border-white/10 bg-[radial-gradient(ellipse_at_top_right,_#123644_0%,_#081120_65%)]">
      <div className="mx-auto grid max-w-6xl items-center gap-12 px-6 py-16 lg:grid-cols-[1.1fr_1fr] lg:py-24">
        <div><p className="text-sm font-medium tracking-wide text-cyan-300">DischargeX · ผู้ช่วยงานสรุปชาร์จสำหรับแพทย์</p><h1 className="mt-6 text-4xl font-semibold leading-tight tracking-tight md:text-5xl">จาก Order Sheet<br/>สู่ร่างสรุปที่<br/><span className="text-cyan-200">พร้อมให้คุณตรวจทาน</span></h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-slate-300">ช่วยจัดข้อมูลการรักษาเป็นหมวด ลดการเริ่มเขียนใหม่ทุกเคส ใช้บนเว็บได้ทันที และต่อกับ Auto สำหรับ HOSxP เมื่อคุณพร้อม</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/app/guest?tutorial=1" className={primary}>ลองตัวอย่างก่อนสมัคร →</Link><Link href="/automator" className="rounded-lg border border-white/25 px-6 py-3 hover:bg-white/5">ดู Auto สำหรับ HOSxP</Link></div><p className="mt-3 text-sm text-slate-400">ดูวิธีใช้ด้วยข้อมูลตัวอย่าง · สมัครเพื่อสร้างสรุปจากข้อมูลของคุณ</p></div>
        <div className="overflow-hidden rounded-xl border border-white/15 bg-slate-900 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 bg-slate-800/80 px-5 py-3 text-xs text-slate-300"><span>DischargeX / ตัวอย่างโครงสร้างผลลัพธ์</span><span className="text-cyan-300">พร้อมตรวจทาน</span></div><div className="space-y-5 p-6"><div className="flex gap-2 text-xs"><span className="rounded bg-cyan-400/10 px-3 py-1 text-cyan-200">Diagnosis</span><span className="rounded bg-white/5 px-3 py-1">การรักษา</span><span className="rounded bg-white/5 px-3 py-1">ติดตาม</span></div>{[["Diagnosis","สรุปการวินิจฉัยจากหลักฐานที่มีในบันทึก"],["Treatment","จัดลำดับการรักษาที่ได้รับระหว่างนอนโรงพยาบาล"],["Outcome & follow-up","แยกผลการรักษาและแผนติดตามให้ตรวจง่าย"]].map(([title,text])=><div key={title} className="border-l-2 border-cyan-500/40 pl-4"><h2 className="font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">{text}</p></div>)}<p className="rounded-md border border-amber-400/20 bg-amber-400/5 p-3 text-xs leading-relaxed text-amber-100">ถ้าข้อมูลไม่ครบ ระบบควรระบุให้ตรวจเพิ่ม คุณเป็นผู้ยืนยันผลก่อนใช้ในเวชระเบียน</p></div></div>
      </div>
    </section>
    <section className="mx-auto max-w-6xl px-6 py-16"><p className="text-sm text-cyan-300">เริ่มจากงานหนึ่งเคส</p><h2 className="mt-2 text-3xl font-semibold">สามช่วงที่คุณมองเห็นและควบคุมได้</h2><div className="mt-8 grid gap-8 md:grid-cols-3">{[["01","วางข้อมูล","นำข้อความ Order Sheet มาใส่ในหน้าสรุป ตรวจข้อมูลระบุตัวบุคคลก่อนส่ง"],["02","สร้างร่างสรุป","AI จัดหัวข้อให้ตามรูปแบบที่เลือก พร้อมจุดที่ควรตรวจเพิ่มเติม"],["03","ตรวจแล้วนำไปใช้","ทบทวน แก้ไข และคัดลอก หรือใช้ Auto ช่วยกรอก HOSxP"]].map(([number,title,text])=><article key={number} className="border-t border-white/20 pt-5"><span className="text-sm text-cyan-300">{number}</span><h3 className="mt-3 text-xl font-semibold">{title}</h3><p className="mt-3 leading-relaxed text-slate-400">{text}</p></article>)}</div><Link href="/learn" className="mt-7 inline-block text-cyan-300 underline underline-offset-4">ดูภาพแนะนำทีละขั้น ไม่ต้องเปิดเสียง →</Link></section>
    <section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-14 md:grid-cols-2"><div><p className="text-sm text-cyan-300">สำหรับงานหลายเคสบน Windows</p><h2 className="mt-3 text-3xl font-semibold">ใช้ HOSxP อยู่?<br/>ให้ Auto ช่วยงานที่ต้องกดซ้ำ</h2></div><div><p className="leading-relaxed text-slate-300">ตั้งค่าให้ตรงกับเครื่องครั้งแรก แล้วให้โปรแกรมช่วยอ่าน สรุป และกรอกทีละช่วง เห็นสถานะตลอด พักด้วย F9 หรือหยุดด้วย F10 ได้</p><Link href="/automator" className="mt-6 inline-block rounded-lg border border-cyan-300/40 px-5 py-3 text-cyan-200">ดูวิธีติดตั้งและดาวน์โหลด →</Link></div></div></section>
    <ImpactStats/><ValueCalculator/>
    <section className="mx-auto max-w-6xl px-6 py-14"><div className="grid gap-8 md:grid-cols-2"><div><h2 className="text-2xl font-semibold">เลือกตามจังหวะงานของคุณ</h2><p className="mt-4 leading-relaxed text-slate-300">ดูโควตาและรายละเอียดแพ็กเกจก่อนตัดสินใจ ใช้บัญชีเดียวกันบนเว็บและโปรแกรม พร้อมดูประวัติการใช้งานและจัดการการชำระเงินได้</p><Link href="/pricing" className="mt-5 inline-block text-cyan-300 underline">ดูราคาและสิทธิ์ปัจจุบัน →</Link></div><div><h2 className="text-2xl font-semibold">ความรู้ที่กลับมาเปิดดูได้</h2><p className="mt-4 leading-relaxed text-slate-300">อ่านแนวทางสรุปชาร์จและทบทวนการลงข้อมูล พร้อมแหล่งอ้างอิงที่ใช้ประกอบการพิจารณา</p><Link href="/knowledge" className="mt-5 inline-block text-cyan-300 underline">เปิดคลังความรู้ →</Link></div></div></section>
    <section className="border-t border-white/10 px-6 py-16 text-center"><h2 className="text-3xl font-semibold">ลองดูว่าเข้ากับงานของคุณไหม</h2><p className="mx-auto mt-4 max-w-xl leading-relaxed text-slate-300">เริ่มจากข้อมูลตัวอย่าง ดูผลลัพธ์และขั้นตอนก่อน แล้วค่อยสมัครเพื่อทดลองสรุปเคสของคุณ</p><Link href="/app/guest?tutorial=1" className={primary+" mt-7"}>เริ่มดูตัวอย่าง</Link></section>
  </main>;
}
