export type KnowledgeReference = {
  id: string;
  title: string;
  year?: string;
  /** Official portal / PDF when available */
  url?: string;
};

export type DiseaseSummary = {
  slug: string;
  name: string;
  version?: string;
  effectiveDate?: string;
  deprecated?: boolean;
  aliases: string[];
  diagnosisToWrite: string[];
  thinkWhen: string[];
  considerMore: string[];
  notYetDiagnosis: string[];
  investigations: string[];
  icd10: string[];
  icd9?: string[];
  seeAlso: string[];
  refs: string[];
  chartChecklist?: {
    mustHave: string[];
    supporting?: string[];
    avoidIf: string[];
  };
};

export const KNOWLEDGE_REFERENCES: KnowledgeReference[] = [
  {
    id: "R1",
    title:
      "CODING AUDIT 2562 (ชุดตรวจสอบรหัสโรค / กรมการแพทย์) และเอกสารคู่ขนาน เช่น การให้รหัสสำหรับ รพ.สต. 2567",
    year: "2019",
  },
  {
    id: "R2",
    title: "Guideline for Medical Document Audit 2019 / คู่มือแนวทางปฏิบัติในการตรวจสอบเอกสารหลักฐาน ปี 2562",
    year: "2019",
  },
  { id: "R3", title: "Medical Record Audit Guideline 2563 (คู่มือ MRA 2563)" },
  { id: "R4", title: "การสรุปเวชระเบียน 2020 CASE MEDICINE", year: "2020" },
  { id: "R5", title: "แนวทางสรุปโรคและหัตถการเพื่อเบิกจ่าย DRGs ออนไลน์ ปี 2566", year: "2023" },
  { id: "R6", title: "แนวทางการบันทึกเวชระเบียนสำหรับแพทย์ ปี 2568", year: "2025" },
  {
    id: "R7",
    title: "สำนักงานหลักประกันสุขภาพแห่งชาติ (สปสช.) — ประกาศ/คู่มือที่เกี่ยวกับเวชระเบียนและสิทธิประโยชน์",
    year: "2026",
    url: "https://www.nhso.go.th/",
  },
  {
    id: "R8",
    title: "แนวทางการทบทวนคุณภาพการบันทึกเวชระเบียน (Peer Reviews) ปี 2568",
    year: "2025",
  },
];

export const DISEASE_SUMMARIES: DiseaseSummary[] = [
  {
    slug: "sepsis-septic-shock",
    name: "Sepsis / Septic shock",
    aliases: ["sepsis", "septic shock", "ไข้ติดเชื้อ", "septicemia"],
    diagnosisToWrite: ["Sepsis, unspecified organism (A41.9)", "Severe sepsis (R65.1)", "Septic shock (R57.2)"],
    thinkWhen: [
      "มีเกณฑ์ SIRS อย่างน้อย 2 ใน 4 ข้อ ร่วมกับมี source หรือสงสัย infection ชัด",
      "SIRS criteria: (1) BT > 38C หรือ < 36C, (2) PR > 90/min, (3) RR > 24/min หรือ PaCO2 < 32 mmHg, (4) WBC > 12,000 หรือ < 4,000 หรือ band form > 10%",
      "Severe sepsis (R65.1) พิจารณาเมื่อมี organ dysfunction >= 2 ระบบ เช่น hypotension, oliguria, hypoxemia, thrombocytopenia, metabolic acidosis ตามเกณฑ์เอกสาร",
    ],
    considerMore: [
      "ถ้าทราบ source ชัด (เช่น pneumonia, pyelonephritis, cholangitis) ให้ใช้ source เป็น principal diagnosis แล้วเพิ่ม Sepsis/Septic shock",
      "Septic shock ต้องมี hypotension + poor perfusion หลังได้ fluid พอ หรือจำเป็นต้องใช้ vasopressor",
      "แนวทาง CODING AUDIT: sepsis ต้องมี clinical infection + SIRS และบริบทการรักษาสอดคล้อง (เช่น ATB ต่อเนื่อง); หากให้ ATB สั้นมากแล้วอาการหายเร็วให้ทบทวนว่าเป็น fever/infection เฉพาะที่แทน",
    ],
    notYetDiagnosis: [
      "ไม่ลง Sepsis ถ้ามีแค่ไข้แต่ยังไม่เข้า SIRS หรือยังไม่ชัดว่าเป็น infection",
      "ไม่ลง Septic shock ถ้ายังไม่มี hypotension/perfusion criteria สนับสนุน",
    ],
    investigations: ["CBC", "Blood culture ก่อน antibiotics เมื่อทำได้", "Lactate", "Renal/liver profile", "CXR หรือ imaging ตาม source"],
    icd10: ["A41.9", "R65.1", "R57.2"],
    seeAlso: ["pneumonia", "acute-respiratory-failure", "acute-diarrhea"],
    refs: ["R1", "R2", "R4", "R5"],
    chartChecklist: {
      mustHave: [
        "SIRS >= 2 criteria + สงสัย/พบ infection source",
        "มี physician diagnosis ในเวชระเบียนและมีการรักษาสอดคล้อง",
      ],
      supporting: [
        "ส่ง blood culture ก่อน antibiotic เมื่อทำได้",
        "ถ้าทราบ source ชัด ให้ source เป็น principal แล้วลง sepsis/septic shock เป็น secondary ตามเกณฑ์",
        "septic shock ต้องมี hypotension + poor perfusion หลัง fluid พอ หรือจำเป็นต้องใช้ vasopressor",
      ],
      avoidIf: [
        "มีแค่ไข้ แต่ยังไม่เข้า SIRS หรือยังไม่ชัดว่าเป็น infection",
        "ไม่มีหลักฐาน hypotension/perfusion criteria แต่ลง septic shock",
      ],
    },
  },
  {
    slug: "pneumonia",
    name: "Pneumonia",
    aliases: ["pneumonia", "ปอดอักเสบ", "aspiration pneumonia", "HAP", "VAP"],
    diagnosisToWrite: [
      "Pneumonia, unspecified organism (J18.9) - ใช้เมื่อวินิจฉัยปอดอักเสบได้ แต่ยังระบุชนิดเชื้อไม่ได้",
      "Bacterial pneumonia, unspecified (J15.9) - ใช้เมื่อภาพรวมเข้ากับ bacterial pneumonia แต่ยังไม่ระบุเชื้อจำเพาะ",
      "Viral pneumonia, unspecified (J12.9) - ใช้เมื่อภาพรวมเข้ากับ viral pneumonia หรือมีผลตรวจไวรัสสนับสนุน",
      "Aspiration pneumonia (J69.0) - ใช้เมื่อมีประวัติ/ความเสี่ยงสำลักและภาพทางคลินิกหรือภาพถ่ายรังสีสอดคล้อง",
      "Acute respiratory failure (J96.0) - เพิ่มร่วมเมื่อมี hypoxemia หรือจำเป็นต้องใช้ respiratory support ตามเกณฑ์",
    ],
    thinkWhen: [
      "มีอาการเข้าได้ เช่น ไข้ ไอ หอบ เสมหะ เจ็บหน้าอก/pleuritic pain ร่วมกับ CXR เข้าได้กับ pneumonia",
      "เกณฑ์ที่ใช้บ่อยจาก CODING AUDIT 2562: อาการเฉียบพลัน (< 2 สัปดาห์) และ CXR พบ new infiltration (หรือแรกรับปกติแต่ follow-up ผิดปกติ)",
      "กรณี bacterial pneumonia ควรมีหลักฐานเชื้อจาก true sputum/gram stain/culture สนับสนุน",
    ],
    considerMore: [
      "ถ้า O2 sat < 90% หรือ PaO2 < 55 หรือจำเป็นต้องใส่ท่อ/ventilator ให้เพิ่ม Acute respiratory failure (J96.0)",
      "ถ้ามี COPD ร่วมและรับไว้รักษาเพราะปอดอักเสบเป็นหลัก ให้ใช้ Pneumonia เป็น principal diagnosis และลง COPD exacerbation เป็น secondary",
      "ถ้า gram stain/culture สนับสนุน bacterial cause ให้พิจารณา Bacterial pneumonia (J15.9)",
      "ถ้าทราบเชื้อชัดเจน ควรระบุ pneumonia ตามเชื้อแทนคำกว้าง",
      "ถ้ามี dysphagia/stroke/feeding tube/aspiration risk ให้คิด aspiration pneumonia",
      "หากเป็น HAP/VAP ให้เขียนคำเต็มใน summary และพิจารณา Y95 ตามบริบท",
    ],
    notYetDiagnosis: [
      "ไม่ลง Bacterial pneumonia จาก WBC สูงอย่างเดียว",
      "ไม่ใช้คำย่อ CAP/HAP ใน summary",
    ],
    investigations: ["CXR", "CBC", "SpO2/ABG เมื่อ severe", "Sputum/gram/culture เมื่อเหมาะสม"],
    icd10: ["J18.9", "J15.9", "J12.9", "J69.0", "J96.0"],
    seeAlso: ["sepsis-septic-shock", "acute-respiratory-failure"],
    refs: ["R2", "R4", "R5"],
    chartChecklist: {
      mustHave: [
        "อาการเข้าได้กับปอดอักเสบ + CXR สนับสนุน (new infiltration หรือ follow-up ผิดปกติ)",
        "ระบุชนิด pneumonia ให้สอดคล้องกับหลักฐานที่มี",
      ],
      supporting: [
        "มีหลักฐานเชื้อจาก true sputum/gram stain/culture -> พิจารณา bacterial/specific organism",
        "มี aspiration risk (dysphagia, stroke, feeding tube) -> พิจารณา aspiration pneumonia",
        "O2 sat < 90% หรือ PaO2 < 55 หรือใช้ ventilator -> เพิ่ม ARF (J96.0)",
      ],
      avoidIf: ["ยังไม่มีภาพรังสีสนับสนุน แต่รีบลง pneumonia ในผู้ใหญ่", "ลง bacterial pneumonia จาก WBC สูงอย่างเดียว"],
    },
  },
  {
    slug: "acute-diarrhea",
    name: "Acute diarrhea",
    aliases: ["acute diarrhea", "infectious diarrhea", "acute infectious diarrhea", "food poisoning", "gastroenteritis"],
    diagnosisToWrite: [
      "Acute diarrhea, unspecified (A09.9) - ใช้เมื่อแพทย์วินิจฉัย acute diarrhoea/diarrhea โดยไม่ระบุรายละเอียดเพิ่ม หรือยังไม่แยกสาเหตุ/เชื้อชัด (คู่กับ narrative ที่หลีกเลี่ยงคำว่า AGE)",
      "Acute infectious diarrhea (A09.0) - ใช้เมื่อตรวจไม่พบสาเหตุอื่นชัดนอกจากการติดเชื้อ และแพทย์วินิจฉัยตามบริบท (ชื่อ ICD: infectious gastroenteritis and colitis, unspecified)",
      "Bacterial intestinal infection, unspecified (A04.9) - ใช้เมื่อ stool มี WBC หรือหลักฐานชี้แบคทีเรีย; ถ้าเพาะเชื้อได้ให้ลงตามเชื้อ (เช่น A00, A03, A06)",
      "Drug-induced noninfective gastroenteritis and colitis (K52.1) - ใช้เมื่อสัมพันธ์กับยา (+ รหัสยา Y57.- ตามเอกสารต้นทางเมื่อมี)",
      "Noninfective gastroenteritis and colitis, unspecified (K52.9) - ใช้เมื่อแพทย์วินิจฉัย noninfectious diarrhea",
    ],
    thinkWhen: [
      "ค่าเริ่มต้นการสรุปเวชระเบียนไทย: ถ้าเป็นโรคหลักจากถ่ายเหลวเฉียบพลันและยังไม่มีหลักฐานแยกเชื้อ/กลไกชัด ให้เน้น Acute diarrhea (A09.9) ใน narrative และเลือกรหัสให้สอดคล้องหลักฐาน",
      "ถ่ายเหลวเฉียบพลัน ยังแยกสาเหตุไม่ได้ชัดเจน ให้ใช้ Acute diarrhea, unspecified (A09.9)",
      "มีไข้/ปวดบิด/ถ่ายมูกเลือด/สงสัยติดเชื้อทาง GI โดยยังไม่ยืนยันชนิดเชื้อ พิจารณา A09.0 ตามบริบท — อย่าใช้คำว่า AGE หรือ acute gastroenteritis เป็นคำนำใน summary",
      "มีหลักฐานชี้ไปทางเชื้อแบคทีเรีย (เช่น stool WBC เด่น, เพาะเชื้อได้, ภาพทางคลินิกเข้าได้) ให้พิจารณา Bacterial intestinal infection (A04.9)",
      "มีบริบทไม่ติดเชื้อชัด เช่น adverse drug effect, ischemic/inflammatory/noninfective cause ใช้ K52.1 หรือ K52.9 ตามความเหมาะสม",
      "CODING AUDIT 2562 (กลุ่ม diarrhea): โดยทั่วไปไม่บันทึก dehydration, postural hypotension, prerenal azotemia, hypokalemia เป็น Sdx — ยกเว้น hypokalemia เมื่อ K < 2.5 และ hyponatremia เมื่อ Na < 125 (พร้อมการรักษา); hypovolemic shock (R57.1) บันทึกเป็น Sdx ได้เมื่อเข้าเกณฑ์",
      "เอกสารการให้รหัส รพ.สต. 2567: ภาวะ dehydration จากท้องเสียมักถือเป็นอาการของโรคหลัก ไม่จำเป็นต้องบันทึกเป็นวินิจฉัยร่วมแยก",
    ],
    considerMore: [
      "K < 2.5 + มีการรักษา -> Hypokalemia (E87.6), Na < 125 + มีการรักษา -> Hyponatremia (E87.1) — สอดคล้องเกณฑ์ใน CODING AUDIT 2562",
      "ถ้ามี hypotension + poor perfusion + ได้ fluid มากหรือใช้ vasopressor ให้คิด Hypovolemic shock (R57.1)",
      "Diarrhea + shock + AKI: prerenal azotemia (R39.2) ไม่ลงนอกจากเข้าเกณฑ์ ARF — เมื่อเข้าเกณฑ์ acute renal failure ใช้ N17.9 (ตามคำตอบในเอกสาร รพ.สต. 2567)",
    ],
    notYetDiagnosis: [
      "ไม่ใช้คำว่า AGE หรือ acute gastroenteritis ใน summary (แม้จะใช้รหัส A09.0 ได้เมื่อบริบทติดเชื้อ — แยก wording กับรหัส)",
      "ไม่ลง AKI/Prerenal/Hypovolemic shock จากแลบอย่างเดียวโดยไม่มีบริบททางคลินิกและการรักษาที่สอดคล้อง",
      "ไม่ลง E86 dehydration เป็นวินิจฉัยร่วมจากอาการท้องเสียอย่างเดียว (ยึด CODING AUDIT 2562 / SCG รพ.สต.)",
    ],
    investigations: ["Electrolytes", "Creatinine/BUN", "CBC", "Stool exam/culture เมื่อสงสัยเชื้อ", "ประเมิน dehydration/poor perfusion"],
    icd10: ["A09.9", "A09.0", "A04.9", "K52.1", "K52.9", "E87.6", "E87.1"],
    seeAlso: ["hypovolemic-shock", "aki-acute-renal-failure"],
    refs: ["R1", "R2", "R4", "R5", "R6", "R7", "R8"],
    chartChecklist: {
      mustHave: [
        "แยกสาเหตุให้ชัดก่อนเลือกรหัส (unspecified / infectious / bacterial / drug-induced / noninfectious)",
        "หลักฐานการดูแลรักษาสอดคล้องกับ diagnosis ที่ลง",
        "narrative ใช้ Acute diarrhea / Infectious diarrhea ตามหลักฐาน — ไม่ใช้ AGE",
      ],
      supporting: [
        "stool WBC หรือผลเพาะเชื้อช่วยสนับสนุน bacterial/infectious cause",
        "K < 2.5 + มีการรักษา -> Hypokalemia",
        "Na < 125 + มีการรักษา -> Hyponatremia",
      ],
      avoidIf: [
        "ใช้คำย่อ AGE ใน summary",
        "ลงโรคร่วมจาก lab อย่างเดียวโดยไม่มี clinical context และการรักษา",
        "ลง dehydration / postural hypotension / prerenal azotemia / hypokalemia เป็น Sdx ในกลุ่มท้องเสีย โดยไม่เข้าเกณฑ์ยกเว้นของ CODING AUDIT",
      ],
    },
  },
  {
    slug: "dengue",
    name: "Dengue",
    aliases: ["dengue", "ไข้เลือดออก", "dengue shock syndrome"],
    diagnosisToWrite: [
      "Dengue without warning signs (A97.0) - ใช้เมื่อยืนยัน dengue และยังไม่มี warning signs",
      "Dengue with warning signs (A97.1) - ใช้เมื่อมี warning signs ตามเกณฑ์",
      "Severe dengue / Dengue shock syndrome (A97.2) - ใช้เมื่อมี shock หรือ severe organ involvement",
      "Dengue, unspecified (A97.9) - ใช้เมื่อวินิจฉัย dengue ได้แต่ข้อมูลยังไม่พอจัดระดับ",
      "Thrombocytopenia (D69.6) - เพิ่มเมื่อมี platelet transfusion หรือมีบริบทการรักษารองรับ",
    ],
    thinkWhen: [
      "ไข้ร่วมกับอาการเข้าได้ และมีผล NS1/serology/lab สนับสนุน",
      "เกณฑ์จาก CODING AUDIT 2562 ที่ช่วยแยก DHF: Hct > 45% หรือเพิ่ม > 20% จาก baseline หรือมี pleural effusion",
      "warning signs ที่ใช้แยก A97.1 ได้แก่ ปวดท้องมาก, อาเจียนมาก, เลือดออกทางเยื่อบุ, ซึม, ตับโต หรือมีหลักฐาน plasma leakage (ยังไม่ถึง shock)",
      "ถ้ามี BP ต่ำ, pulse pressure แคบ, poor perfusion หรือเข้าได้กับ shock ให้จัดเป็น Severe dengue / Dengue shock syndrome (A97.2)",
      "ถ้าข้อมูลยังไม่พอแยกระดับ ใช้ Dengue, unspecified (A97.9)",
    ],
    considerMore: [
      "ถ้ามี platelet transfusion ให้เพิ่ม Thrombocytopenia (D69.6) และอย่าลืมสรุปหัตถการ transfusion",
      "ถ้ามี pleural effusion หรือ plasma leakage ชัด ให้ใช้ช่วยแยกระดับความรุนแรง",
      "ชุดข้อมูลนี้ยังไม่กำหนดตัวเลข cutoff (เช่น Hct/platelet) เอง เพื่อหลีกเลี่ยงการมโนเกณฑ์ ต้องยึดเอกสารอ้างอิงของหน่วยงาน",
      "CODING AUDIT 2562 ยังอ้าง Dengue fever (A90) / DHF (A91) — ICD-10 ไทยรุ่นปัจจุบันใช้กลุ่ม A97.x; ตรวจสอบเวอร์ชันรหัสที่หน่วยงาน/สปสช. กำหนด",
    ],
    notYetDiagnosis: [
      "ไม่ลง Dengue หากยังไม่มีข้อมูลสนับสนุนพอ",
      "ไม่ลง Dengue with warning signs ถ้ายังไม่มี warning signs หรือหลักฐาน plasma leakage สนับสนุน",
      "ไม่ลง severe dengue ถ้ายังไม่มี shock/หลักฐานความรุนแรง",
      "ไม่ลง Thrombocytopenia หากมีแค่ platelet ต่ำแต่ยังไม่มีการรักษาเฉพาะหรือบริบทรองรับ",
    ],
    investigations: ["CBC/platelet trend", "NS1/serology", "Hematocrit trend", "ประเมิน plasma leakage", "วัด pulse pressure/สัญญาณ poor perfusion ในรายเสี่ยง severe dengue"],
    icd10: ["A97.0", "A97.1", "A97.2", "A97.9"],
    seeAlso: ["hypovolemic-shock", "pleural-effusion"],
    refs: ["R1", "R2", "R4", "R5"],
    chartChecklist: {
      mustHave: [
        "มีข้อมูลสนับสนุน dengue (clinical + NS1/serology/lab)",
        "แยกระดับให้ชัด: ไม่มี warning signs / มี warning signs / severe (shock)",
      ],
      supporting: [
        "เกณฑ์ DHF ที่ใช้บ่อย: Hct > 45% หรือเพิ่ม > 20% หรือมี pleural effusion",
        "มี BP ต่ำ, pulse pressure แคบ, poor perfusion -> พิจารณา severe dengue",
        "มี platelet transfusion -> พิจารณาเพิ่ม thrombocytopenia และหัตถการ",
      ],
      avoidIf: [
        "ยังไม่มี warning signs หรือ plasma leakage แต่ลง A97.1",
        "ยังไม่มี shock/ความรุนแรงพอ แต่ลง severe dengue",
      ],
    },
  },
  {
    slug: "aki-acute-renal-failure",
    name: "AKI / Acute renal failure",
    aliases: ["aki", "acute renal failure", "prerenal", "acute on ckd"],
    diagnosisToWrite: ["Acute renal failure (N17.9)", "Prerenal azotemia (R39.2)", "Acute on top chronic renal failure"],
    thinkWhen: [
      "Creatinine เพิ่ม > 0.3 mg/dL ใน 48 ชม. หรือ >= 50% ใน 1 สัปดาห์ หรือ urine output < 0.5 mL/kg/hr > 6 ชม.",
      "Prerenal azotemia (R39.2) พิจารณาเมื่อมีภาวะ volume depletion/shock รองรับและแนวโน้มดีขึ้นหลังแก้ไข volume",
    ],
    considerMore: [
      "ถ้ามี CKD เดิมและ AKI ซ้อน ให้แยก Pdx/Sdx ให้ชัด",
      "ถ้ามีสาเหตุเฉพาะของ ARF ให้ใช้สาเหตุนั้นเป็น principal diagnosis",
      "ถ้าเป็น CKD stage 5 ให้ระบุ ESRD (N18.5) ตามบริบทร่วม",
    ],
    notYetDiagnosis: ["ไม่ลง ARF ถ้ามีแค่ BUN/Cr สูง", "ไม่ลง Acute on CKD ถ้าไม่ทราบ baseline หรือไม่มีหลักฐานไตเรื้อรังเดิม"],
    investigations: ["Creatinine trend", "Urine output", "Electrolytes", "ประเมิน volume status / shock"],
    icd10: ["N17.9", "R39.2", "N18.9", "N18.5"],
    seeAlso: ["acute-diarrhea", "hypovolemic-shock", "ckd-esrd"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: [
        "เข้าเกณฑ์ AKI: Cr เพิ่ม > 0.3 ใน 48 ชม. หรือ >= 50% ใน 1 สัปดาห์ หรือ urine output < 0.5 mL/kg/hr > 6 ชม.",
        "มีการวินิจฉัยและการดูแลรักษาสอดคล้อง",
      ],
      supporting: [
        "มี CKD เดิม -> แยก acute on chronic ให้ชัดใน Pdx/Sdx",
        "Prerenal พิจารณาเมื่อมี volume depletion/shock และตอบสนองต่อการแก้ไข volume",
      ],
      avoidIf: ["มีแค่ BUN/Cr สูงอย่างเดียวโดยไม่มี clinical criteria รองรับ", "ไม่ทราบ baseline แต่ลง acute on CKD แบบจำเพาะเกินข้อมูล"],
    },
  },
  {
    slug: "hypovolemic-shock",
    name: "Hypovolemic shock",
    aliases: ["hypovolemic shock", "shock from volume loss", "ช็อกจากขาดน้ำ/เสียเลือด"],
    diagnosisToWrite: ["Hypovolemic shock (R57.1)"],
    thinkWhen: [
      "SBP < 90 หรือ drop > 40 หรือ MAP < 60 + poor perfusion และเข้าได้กับ volume loss/dehydration/bleeding",
      "poor perfusion ที่พบบ่อย: confusion, oliguria, delayed capillary refill, metabolic acidosis",
    ],
    considerMore: [
      "ควรมีการรักษาจริง (fluid resuscitation/vasopressor ตามบริบท)",
      "แยกสาเหตุหลัก เช่น diarrhea, GI bleeding, PPH, trauma",
      "โดยทั่วไปควรตอบสนองต่อ fluid เหมาะสมในช่วงแรกของการกู้ชีพ",
    ],
    notYetDiagnosis: ["ไม่ลง shock ถ้ายังไม่มี hypotension/perfusion criteria ครบ", "ไม่ลงจากค่าความดันต่ำครั้งเดียวโดยไม่มีบริบท"],
    investigations: ["Vital sign trend", "Perfusion markers", "Lactate", "Urine output"],
    icd10: ["R57.1"],
    seeAlso: ["acute-diarrhea", "gi-bleeding", "postpartum-hemorrhage"],
    refs: ["R1", "R2", "R5"],
    chartChecklist: {
      mustHave: ["ความดันเข้าเกณฑ์ shock + poor perfusion", "มีเหตุ volume loss/dehydration/bleeding รองรับ"],
      supporting: ["มีการกู้ชีพด้วย fluid/vasopressor ตามบริบท", "มีการติดตาม perfusion markers และ urine output"],
      avoidIf: ["ความดันต่ำครั้งเดียวโดยไม่มี clinical context", "ไม่มีหลักฐาน poor perfusion แต่ลง shock"],
    },
  },
  {
    slug: "acute-respiratory-failure",
    name: "Acute respiratory failure",
    aliases: ["arf", "respiratory failure", "หายใจล้มเหลวเฉียบพลัน"],
    diagnosisToWrite: ["Acute respiratory failure (J96.0)"],
    thinkWhen: [
      "O2 sat < 90% หรือ PaO2 < 55 หรือจำเป็นต้องใส่ท่อ/ventilator/ambu support",
      "ในราย refer ที่ยังต้องใช้ ventilator ต่อเนื่องแม้พยายาม wean แล้วไม่สำเร็จ ยังสนับสนุน ARF",
    ],
    considerMore: ["แยก underlying cause เช่น pneumonia/COPD/asthma/heart failure"],
    notYetDiagnosis: ["ไม่ลง ARF ถ้าไม่มี hypoxemia หรือไม่ได้ต้องการ respiratory support จริง"],
    investigations: ["SpO2", "ABG", "CXR", "Respiratory support requirement"],
    icd10: ["J96.0"],
    seeAlso: ["pneumonia", "sepsis-septic-shock"],
    refs: ["R1", "R2", "R4", "R5"],
    chartChecklist: {
      mustHave: ["เข้าเกณฑ์ hypoxemia (เช่น O2 sat < 90% หรือ PaO2 < 55) หรือจำเป็นต้อง respiratory support", "มีการวินิจฉัยและการรักษาสอดคล้อง"],
      supporting: ["ABG/SpO2 trend รองรับ", "ระบุสาเหตุหลักของ ARF ร่วม (pneumonia/COPD/asthma/HF)"],
      avoidIf: ["ยังไม่พบ hypoxemia และไม่ต้องการ respiratory support", "ลง ARF จาก CXR/อาการอย่างเดียวโดยไม่มีเกณฑ์ออกซิเจนรองรับ"],
    },
  },
  {
    slug: "gi-bleeding",
    name: "GI bleeding",
    aliases: ["gi bleeding", "hematemesis", "melena", "hematochezia"],
    diagnosisToWrite: [
      "Gastrointestinal hemorrhage, unspecified (K92.2) - ใช้เมื่อมี GI bleeding แต่ยังไม่ระบุตำแหน่งชัด",
      "Hematemesis (K92.0) - ใช้เมื่อเด่นเป็นอาเจียนเป็นเลือด",
      "Melena (K92.1) - ใช้เมื่อเด่นเป็นถ่ายดำ",
    ],
    thinkWhen: [
      "มีเลือดออกทาง GI และยังไม่ระบุตำแหน่งชัด ใช้ K92.2",
      "ถ้าพบ ulcer/varix จาก EGD ให้ระบุโรคนั้น with hemorrhage",
      "ถ้ามีทั้ง hematemesis และ melena ให้เลือกอาการเด่นตามเอกสารต้นทาง",
    ],
    considerMore: [
      "ถ้าต้องให้เลือดและมีภาวะซีดจากเสียเลือดเฉียบพลัน ให้พิจารณา Acute posthemorrhagic anemia (D62)",
      "ถ้ามี hypovolemic shock หรือมีหัตถการ EGD/transfusion ให้สรุปร่วมตามบริบท",
    ],
    notYetDiagnosis: ["ไม่ลง D62 ถ้ายังไม่มีข้อมูลเสียเลือดเฉียบพลันชัดและยังไม่ถึงระดับต้องรักษาเหมาะสม"],
    investigations: ["CBC trend", "EGD findings", "Hemodynamic monitoring"],
    icd10: ["K92.2", "K92.0", "K92.1", "D62"],
    seeAlso: ["hypovolemic-shock", "cirrhosis-of-liver"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐานเลือดออกทาง GI ชัด", "เลือกรหัสอาการหลัก/ตำแหน่งให้สอดคล้องข้อมูลที่มี"],
      supporting: ["EGD/ภาพรอยโรคช่วยระบุ with hemorrhage ให้จำเพาะ", "ถ้ามีเสียเลือดมากและให้เลือด พิจารณา D62 + transfusion procedure"],
      avoidIf: ["รีบลง D62 โดยไม่มีหลักฐานเสียเลือดเฉียบพลันและการรักษาสอดคล้อง"],
    },
  },
  {
    slug: "acute-bronchitis",
    name: "Acute bronchitis",
    aliases: ["acute bronchitis", "หลอดลมอักเสบเฉียบพลัน"],
    diagnosisToWrite: ["Acute bronchitis (J20.9)"],
    thinkWhen: ["ไอเฉียบพลันและอาการทางหลอดลมเข้าได้ แต่ยังไม่มีหลักฐานพอสำหรับ pneumonia"],
    considerMore: ["ในผู้ใหญ่หากยังไม่มี CXR สนับสนุน ไม่ควรรีบลง pneumonia"],
    notYetDiagnosis: ["ไม่ลง pneumonia ถ้ายังไม่มีข้อมูลติดเชื้อปอด/ภาพรังสีสนับสนุนเพียงพอ"],
    investigations: ["CXR ตามข้อบ่งชี้", "ตรวจร่างกายระบบหายใจ", "SpO2 เมื่อมีหอบ"],
    icd10: ["J20.9"],
    seeAlso: ["pneumonia", "asthma-exacerbation", "copd-acute-exacerbation"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["ไอเฉียบพลันและอาการทางหลอดลมเข้าได้", "ยังไม่มีข้อมูลพอสำหรับ pneumonia"],
      supporting: ["CXR ปกติ/ยังไม่พบหลักฐาน infiltration ช่วยสนับสนุน bronchitis"],
      avoidIf: ["มีหลักฐานปอดอักเสบชัดแต่ยังลงเป็น bronchitis กว้างๆ"],
    },
  },
  {
    slug: "copd-acute-exacerbation",
    name: "COPD with acute exacerbation",
    aliases: ["copd exacerbation", "copd", "ถุงลมโป่งพองกำเริบ"],
    diagnosisToWrite: [
      "Chronic obstructive pulmonary disease with acute lower respiratory infection (J44.0) - ใช้เมื่อ COPD กำเริบร่วมกับ LRTI",
      "Chronic obstructive pulmonary disease with acute exacerbation, unspecified (J44.1) - ใช้เมื่อเป็น AECOPD โดยยังไม่ระบุ LRTI",
      "Chronic obstructive pulmonary disease, unspecified (J44.9) - ใช้เมื่อเป็นโรคประจำตัว COPD โดยไม่มีข้อมูลกำเริบชัด",
      "Acute respiratory failure (J96.0) - เพิ่มร่วมเมื่อเข้าเกณฑ์ hypoxemia/respiratory support",
    ],
    thinkWhen: [
      "มีประวัติ COPD เดิมและมีอาการกำเริบชัด -> พิจารณา J44.1",
      "ถ้ามี lower respiratory infection ร่วม -> พิจารณา J44.0",
      "ข้อมูลสนับสนุน COPD ได้แก่ ไอ/เสมหะ/หอบเรื้อรัง, wheezing/dyspnea, CXR เข้าได้กับ emphysema/chronic bronchitis หรือ pulmonary function test พบ FEV1/FVC < 70%",
      "กรณี new case ควรมี spirometry หรือข้อมูลยืนยันที่เพียงพอ",
    ],
    considerMore: [
      "กรณี COPD ร่วม pneumonia: โดยทั่วไปให้ใช้ Pneumonia เป็น principal diagnosis และลง COPD with acute exacerbation เป็น secondary diagnosis",
      "หากเหตุรับไว้รักษาหลักเป็น AECOPD ชัด และ pneumonia เป็นภาวะร่วมรอง ให้พิจารณา COPD เป็น principal ได้ โดยต้องสอดคล้องกับ clinical course",
      "new case ควรมีข้อมูลสนับสนุนเพียงพอ เช่น spirometry",
      "ถ้ามี hypoxemia หรือใส่ท่อ/ventilator ให้พิจารณา ARF",
    ],
    notYetDiagnosis: ["ไม่ลง COPD ในรายที่ยังไม่มีหลักฐานเดิมหรือข้อมูลสนับสนุนพอ", "ไม่ลง ARF ถ้ายังไม่เข้าเกณฑ์"],
    investigations: ["SpO2/ABG", "CXR", "ประวัติและการรักษา COPD เดิม", "Spirometry เมื่อเหมาะสม"],
    icd10: ["J44.0", "J44.1", "J44.9", "J96.0"],
    seeAlso: ["pneumonia", "acute-respiratory-failure"],
    refs: ["R1", "R2", "R4", "R5", "R6", "R7", "R8"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน COPD เดิม/ข้อมูลสนับสนุนเพียงพอ", "ระบุว่าเป็น AECOPD หรือ AECOPD with LRTI ให้ชัด"],
      supporting: [
        "new case ควรมี spirometry หรือข้อมูลเทียบเท่าที่ชัด",
        "เข้าเกณฑ์ hypoxemia/ventilator ค่อยเพิ่ม ARF",
        "J44.0 เมื่อมี lower respiratory infection ร่วมกับ COPD กำเริบ — J44.1 เมื่อกำเริบโดยยังไม่ระบุ LRTI",
      ],
      avoidIf: ["ยังไม่มีหลักฐาน COPD เดิม แต่ลง diagnosis จำเพาะทันที", "ลง ARF โดยไม่เข้าเกณฑ์"],
    },
  },
  {
    slug: "asthma-exacerbation",
    name: "Asthma exacerbation",
    aliases: ["asthma attack", "asthma exacerbation", "หอบหืดกำเริบ"],
    diagnosisToWrite: [
      "Asthma with acute exacerbation (J45.9) - ใช้เมื่อมี asthma attack/exacerbation ชัดเจน",
      "Acute respiratory failure (J96.0) - เพิ่มร่วมเมื่อเข้าเกณฑ์ hypoxemia/respiratory support",
    ],
    thinkWhen: ["มีประวัติ asthma และมีอาการกำเริบชัด"],
    considerMore: ["ถ้ามี hypoxemia รุนแรงหรือใส่ท่อ ให้เพิ่ม Acute respiratory failure (J96.0)"],
    notYetDiagnosis: ["ไม่ลง pneumonia หากยังไม่มีข้อมูลติดเชื้อหรือ CXR สนับสนุน"],
    investigations: ["SpO2", "ABG เมื่อ severe", "CXR ตามข้อบ่งชี้"],
    icd10: ["J45.9", "J96.0"],
    seeAlso: ["acute-respiratory-failure", "pneumonia"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["มีประวัติ/บริบท asthma และอาการกำเริบชัด"],
      supporting: ["พิจารณา ARF เมื่อมี hypoxemia หรือจำเป็นต้องใส่ท่อ/ventilator"],
      avoidIf: ["ยังไม่มีข้อมูลติดเชื้อหรือ CXR สนับสนุน แต่รีบลง pneumonia ร่วม"],
    },
  },
  {
    slug: "pleural-effusion",
    name: "Pleural effusion",
    aliases: ["pleural effusion", "น้ำในช่องเยื่อหุ้มปอด"],
    diagnosisToWrite: [
      "Pleural effusion, NEC (J90) - ใช้เมื่อยังไม่ทราบสาเหตุชัด",
      "Pleural effusion in conditions classified elsewhere (J91) - ใช้เมื่อทราบโรคสาเหตุหลักแล้ว",
    ],
    thinkWhen: ["ถ้าทราบสาเหตุจากโรคหลักชัด ให้ลงโรคหลัก + J91", "ถ้ายังไม่ทราบสาเหตุ ใช้ J90"],
    considerMore: ["ถ้ามี thoracentesis/chest tube อย่าลืมสรุปหัตถการ"],
    notYetDiagnosis: ["ไม่ระบุสาเหตุจำเพาะหากยังไม่มีหลักฐานเพียงพอ"],
    investigations: ["CXR/Ultrasound", "ประเมินสาเหตุจากโรคหลัก", "ข้อมูลหัตถการระบาย"],
    icd10: ["J90", "J91"],
    seeAlso: ["pneumonia", "acute-heart-failure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน pleural effusion จาก imaging", "ถ้าทราบสาเหตุหลักชัด ให้ใช้โรคหลัก + J91"],
      supporting: ["มี thoracentesis/chest tube ให้สรุปหัตถการร่วม"],
      avoidIf: ["ยังไม่ทราบสาเหตุแต่ลงรหัสจำเพาะเกินข้อมูล"],
    },
  },
  {
    slug: "ckd-esrd",
    name: "CKD / ESRD",
    aliases: ["ckd", "esrd", "ไตเรื้อรัง"],
    diagnosisToWrite: ["Chronic kidney disease, unspecified (N18.9)", "ESRD (N18.5)"],
    thinkWhen: ["มีข้อมูล CKD เดิมและ stage ชัด", "ถ้า stage 5/ESRD ให้ใช้ N18.5"],
    considerMore: ["หากมี AKI ซ้อนให้แยก acute/chronic ให้ชัดใน Pdx/Sdx"],
    notYetDiagnosis: ["ไม่ลง CKD หากยังไม่มีหลักฐานความเป็นโรคเรื้อรัง"],
    investigations: ["Renal function trend", "Baseline creatinine", "ประวัติ CKD เดิม/การล้างไต"],
    icd10: ["N18.9", "N18.5"],
    seeAlso: ["aki-acute-renal-failure", "hyperkalemia", "anemia"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐานโรคไตเรื้อรังต่อเนื่องและระบุ stage ได้"],
      supporting: ["ถ้า stage 5/ESRD ให้ใช้ N18.5", "แยก AKI ซ้อน CKD ให้ชัดใน Pdx/Sdx"],
      avoidIf: ["ไม่มีหลักฐานความเรื้อรังแต่ลง CKD ทันที"],
    },
  },
  {
    slug: "dehydration",
    name: "Dehydration",
    aliases: ["dehydration", "volume depletion", "ขาดน้ำ"],
    diagnosisToWrite: ["Dehydration (E86)"],
    thinkWhen: ["มี volume depletion ชัด มีข้อมูลสนับสนุน และมีการรักษาจริง"],
    considerMore: ["แยกภาวะร่วม เช่น diarrhea, shock, AKI"],
    notYetDiagnosis: ["ไม่ลง dehydration หากมีแค่ให้สารน้ำทั่วไปโดยไม่มีภาพทางคลินิกชัด"],
    investigations: ["Clinical volume assessment", "Vital signs", "Urine output", "Electrolytes/BUN/Cr"],
    icd10: ["E86"],
    seeAlso: ["acute-diarrhea", "hypovolemic-shock", "aki-acute-renal-failure"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["มีภาพ volume depletion ชัด + การรักษาที่สอดคล้อง"],
      supporting: ["vital signs/urine output/electrolytes สนับสนุนภาวะขาดน้ำ"],
      avoidIf: ["ให้สารน้ำทั่วไปอย่างเดียวโดยไม่มีหลักฐานทางคลินิก"],
    },
  },
  {
    slug: "hypokalemia",
    name: "Hypokalemia",
    aliases: ["hypokalemia", "potassium low", "โพแทสเซียมต่ำ"],
    diagnosisToWrite: ["Hypokalemia (E87.6)"],
    thinkWhen: ["K < 2.5 และมีการรักษา"],
    considerMore: ["ประเมินสาเหตุร่วม เช่น diarrhea, AKI, DKA/HHS"],
    notYetDiagnosis: ["ไม่ลง hypokalemia ถ้า K ยังไม่ถึงเกณฑ์ตามแนวทางที่ใช้งาน"],
    investigations: ["K trend", "ECG เมื่อเหมาะสม", "การรักษาที่ให้จริง"],
    icd10: ["E87.6"],
    seeAlso: ["acute-diarrhea", "aki-acute-renal-failure", "dka-hhs"],
    refs: ["R4", "R6"],
    chartChecklist: {
      mustHave: ["K ต่ำเข้าเกณฑ์และมีการรักษาสอดคล้อง"],
      supporting: ["ติดตาม K ซ้ำ/ECG ในรายรุนแรง"],
      avoidIf: ["ค่า K ยังไม่ถึงเกณฑ์แต่ลง hypokalemia"],
    },
  },
  {
    slug: "hyponatremia",
    name: "Hyponatremia",
    aliases: ["hyponatremia", "sodium low", "โซเดียมต่ำ"],
    diagnosisToWrite: ["Hyponatremia (E87.1)"],
    thinkWhen: ["Na < 125 และมีการรักษา"],
    considerMore: ["ประเมินสาเหตุร่วมและความรุนแรงทางอาการ"],
    notYetDiagnosis: ["ไม่ลง hyponatremia หากยังไม่ถึงเกณฑ์หรือไม่มีการรักษาที่สอดคล้อง"],
    investigations: ["Na trend", "Clinical symptom correlation", "การรักษาที่ให้จริง"],
    icd10: ["E87.1"],
    seeAlso: ["acute-diarrhea", "dka-hhs", "aki-acute-renal-failure"],
    refs: ["R4", "R6"],
    chartChecklist: {
      mustHave: ["Na ต่ำเข้าเกณฑ์ที่ใช้งาน และมีการรักษาสอดคล้อง"],
      supporting: ["ติดตาม Na ซ้ำและประเมินอาการทางคลินิก"],
      avoidIf: ["ยังไม่ถึงเกณฑ์หรือไม่มีการรักษารองรับ"],
    },
  },
  {
    slug: "dka-hhs",
    name: "DKA / HHS",
    aliases: ["dka", "hhs", "diabetic ketoacidosis", "hyperosmolar state"],
    diagnosisToWrite: ["Diabetic ketoacidosis", "Hyperosmolar hyperglycemic state"],
    thinkWhen: ["น้ำตาลสูง + ketone/acidosis เข้าได้ -> DKA", "น้ำตาลสูงมาก + dehydration ชัด + altered consciousness -> HHS"],
    considerMore: ["มองหาภาวะร่วม: AKI, shock, electrolyte imbalance"],
    notYetDiagnosis: ["ไม่สรุป DKA/HHS หากข้อมูล lab/clinical ยังไม่พอแยก"],
    investigations: ["Glucose", "Ketone", "ABG/CO2", "Electrolytes", "Renal function"],
    icd10: ["E10.1", "E11.1", "E13.1", "E14.1"],
    seeAlso: ["aki-acute-renal-failure", "hypokalemia", "hyponatremia", "metabolic-acidosis"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["DKA: น้ำตาลสูง + ketone/acidosis เข้าได้", "HHS: น้ำตาลสูงมาก + dehydration ชัด + altered consciousness"],
      supporting: ["มี ABG/ketone/electrolyte รองรับ", "ประเมินภาวะร่วม AKI/shock/electrolyte imbalance"],
      avoidIf: ["ข้อมูล lab/clinical ยังไม่พอแยก DKA กับ HHS"],
    },
  },
  {
    slug: "metabolic-acidosis",
    name: "Metabolic acidosis",
    aliases: ["metabolic acidosis", "acidosis", "กรดเกินเมตาบอลิก"],
    diagnosisToWrite: ["Metabolic acidosis (E87.2)"],
    thinkWhen: ["มีข้อมูลแล็บสนับสนุน + บริบททางคลินิก + มีการรักษา"],
    considerMore: ["พิจารณาสาเหตุร่วมเช่น shock, AKI, DKA, diarrhea"],
    notYetDiagnosis: ["ไม่ลง metabolic acidosis หากมีแค่ CO2 ต่ำเล็กน้อยโดยไม่มีภาพรวมสนับสนุน"],
    investigations: ["ABG", "Electrolytes/anion gap", "Lactate", "Renal function"],
    icd10: ["E87.2"],
    seeAlso: ["dka-hhs", "aki-acute-renal-failure", "hypovolemic-shock"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน acid-base ผิดปกติ + บริบททางคลินิกและการรักษาสอดคล้อง"],
      supporting: ["ABG, HCO3, anion gap และสาเหตุร่วมช่วยยืนยัน"],
      avoidIf: ["มีแค่ CO2 ต่ำเล็กน้อยโดยไม่มีภาพรวมสนับสนุน"],
    },
  },
  {
    slug: "cirrhosis-of-liver",
    name: "Cirrhosis of liver",
    aliases: ["cirrhosis", "ตับแข็ง", "liver cirrhosis"],
    diagnosisToWrite: ["Cirrhosis of liver (K74.6)", "Hepatic encephalopathy", "Esophageal varices with bleeding (เมื่อเข้าได้)"],
    thinkWhen: [
      "มีข้อมูล clinical/lab/imaging สนับสนุนเพียงพอของ cirrhosis",
      "แนวทางที่ใช้บ่อย: มี stigmata ทางคลินิกหลายข้อร่วมกับ LFT/imaging สนับสนุน",
      "มี altered consciousness ในบริบทโรคตับ -> พิจารณา hepatic encephalopathy",
    ],
    considerMore: ["มองหา GI bleeding/variceal bleeding, shock, anemia และภาวะแทรกซ้อนอื่น", "ถ้ามี variceal bleeding ให้ระบุ with bleeding ให้ชัดตามบริบท"],
    notYetDiagnosis: ["ไม่ลง cirrhosis หากยังไม่มีหลักฐาน clinical/lab/imaging สนับสนุนพอ"],
    investigations: ["LFT", "Ultrasound/CT", "ภาวะแทรกซ้อนจาก portal hypertension", "CBC/coagulation"],
    icd10: ["K74.6", "I85.9", "I85.0", "K72.9"],
    seeAlso: ["gi-bleeding", "hepatic-encephalopathy"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน cirrhosis จาก clinical ร่วมกับ lab/imaging"],
      supporting: ["ประเมินภาวะแทรกซ้อน portal HT, variceal bleeding, hepatic encephalopathy"],
      avoidIf: ["ยังไม่มีหลักฐานสนับสนุนพอ แต่ลง cirrhosis จำเพาะ"],
    },
  },
  {
    slug: "hepatic-encephalopathy",
    name: "Hepatic encephalopathy",
    aliases: ["hepatic encephalopathy", "ตับแข็งลงสมอง"],
    diagnosisToWrite: ["Hepatic encephalopathy"],
    thinkWhen: ["ผู้ป่วยโรคตับมี altered consciousness และภาพรวมเข้าได้"],
    considerMore: ["ประเมิน precipitating factors และโรคร่วมที่เกี่ยวข้อง", "หากไม่มีบริบทโรคตับชัด อย่าลง hepatic encephalopathy จาก altered consciousness อย่างเดียว"],
    notYetDiagnosis: ["ไม่ลง hepatic encephalopathy หาก altered consciousness ยังไม่มีบริบทโรคตับรองรับ"],
    investigations: ["Clinical neurologic assessment", "LFT/ammonia ตามบริบท", "ค้นหาสาเหตุร่วม"],
    icd10: ["K72.9"],
    seeAlso: ["cirrhosis-of-liver", "gi-bleeding"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["ผู้ป่วยโรคตับมี altered consciousness และ clinical context สอดคล้อง"],
      supporting: ["ค้นหา precipitating factors และโรคร่วม"],
      avoidIf: ["ยังไม่มีบริบทโรคตับชัด แต่สรุป hepatic encephalopathy"],
    },
  },
  {
    slug: "acute-heart-failure",
    name: "Acute heart failure / Congestive heart failure",
    aliases: ["acute heart failure", "chf", "heart failure", "หัวใจล้มเหลว"],
    diagnosisToWrite: ["Congestive heart failure (I50.0)", "Left heart failure (I50.1)", "Pulmonary edema (J81)"],
    thinkWhen: ["มีอาการและหลักฐานเข้าได้กับ heart failure", "CHF/LHF ควรมีการวินิจฉัยแพทย์ร่วมกับข้อมูลตรวจและการรักษาที่สอดคล้อง"],
    considerMore: ["ถ้ามี pulmonary edema ชัดให้เพิ่ม J81", "หากมี hypoxemia มากให้พิจารณา ARF", "หากเป็น hypertensive heart disease with heart failure ให้จัดรหัสตามกลุ่มโรคหัวใจความดันสูงอย่างสอดคล้อง"],
    notYetDiagnosis: ["ไม่ลง ARF หากยังไม่เข้าเกณฑ์ hypoxemia/respiratory support"],
    investigations: ["CXR", "SpO2/ABG", "Echo ตามบริบท", "Fluid status"],
    icd10: ["I50.0", "I50.1", "J81", "J96.0"],
    seeAlso: ["pleural-effusion", "acute-respiratory-failure"],
    refs: ["R1", "R2", "R4", "R5"],
    chartChecklist: {
      mustHave: ["มีการวินิจฉัย heart failure โดยแพทย์ + หลักฐานตรวจและการรักษาสอดคล้อง"],
      supporting: ["CXR/Echo/อาการคั่งน้ำหรือหอบช่วยยืนยัน", "มี pulmonary edema ชัด ให้พิจารณา J81"],
      avoidIf: ["ข้อมูลไม่พอ แต่สรุปภาวะ ARF ร่วมโดยไม่เข้าเกณฑ์"],
    },
  },
  {
    slug: "acute-appendicitis",
    name: "Acute appendicitis",
    aliases: ["appendicitis", "acute appendicitis", "ปวดท้อง rlq"],
    diagnosisToWrite: ["Acute appendicitis", "Ruptured appendicitis", "Peritonitis (เมื่อเข้าได้)"],
    thinkWhen: ["RLQ pain + clinical picture เข้าได้ และยืนยันด้วย imaging หรือ operative finding"],
    considerMore: ["ถ้ามี perforation/rupture ให้ระบุ ruptured appendicitis", "ถ้ามี generalized peritonitis ให้เพิ่ม peritonitis"],
    notYetDiagnosis: ["ไม่สรุป appendicitis หากยังไม่มีข้อมูลทางคลินิกหรือ imaging/operative สนับสนุนพอ"],
    investigations: ["CBC", "Ultrasound/CT abdomen", "Operative findings"],
    icd10: ["K35.9", "K36", "K65.0"],
    seeAlso: ["peritonitis", "sepsis-septic-shock"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["อาการเข้าได้กับ appendicitis + imaging/operative finding สนับสนุน"],
      supporting: ["ถ้ามี perforation/rupture ให้ระบุ ruptured appendicitis", "ถ้ามี generalized peritonitis ให้เพิ่ม peritonitis"],
      avoidIf: ["ข้อมูลทางคลินิกหรือ imaging ยังไม่พอ"],
    },
  },
  {
    slug: "peritonitis",
    name: "Peritonitis",
    aliases: ["peritonitis", "เยื่อบุช่องท้องอักเสบ"],
    diagnosisToWrite: ["Peritonitis (K65.0)"],
    thinkWhen: ["มีข้อมูล clinical/operative/imaging เข้าได้กับ peritonitis"],
    considerMore: ["ถ้ามีไข้สูง BP ต่ำ organ dysfunction ให้คิด sepsis เพิ่ม"],
    notYetDiagnosis: ["ไม่ลง peritonitis หากยังไม่มีข้อมูลรองรับเพียงพอ"],
    investigations: ["Clinical abdominal signs", "Imaging", "Operative note"],
    icd10: ["K65.0"],
    seeAlso: ["acute-appendicitis", "sepsis-septic-shock"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน clinical/operative/imaging เข้าได้กับ peritonitis"],
      supporting: ["ประเมิน sepsis ร่วมเมื่อมี organ dysfunction"],
      avoidIf: ["ยังไม่มีข้อมูลรองรับเพียงพอ"],
    },
  },
  {
    slug: "acute-pancreatitis",
    name: "Acute pancreatitis",
    aliases: ["acute pancreatitis", "pancreatitis", "ตับอ่อนอักเสบเฉียบพลัน"],
    diagnosisToWrite: ["Acute pancreatitis (K85.9)"],
    thinkWhen: ["ปวดท้อง + enzyme สูง + imaging เข้าได้กับ pancreatitis"],
    considerMore: ["หากมี organ failure/shock/ARF ให้เพิ่ม diagnosis ตามระบบที่เกี่ยวข้อง"],
    notYetDiagnosis: ["ไม่ลง pancreatitis หากยังไม่มีข้อมูล lab/imaging ที่สอดคล้องเพียงพอ"],
    investigations: ["Amylase/Lipase", "Ultrasound/CT abdomen", "Clinical severity assessment"],
    icd10: ["K85.9"],
    seeAlso: ["aki-acute-renal-failure", "hypovolemic-shock", "acute-respiratory-failure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["ปวดท้อง + enzyme สูง + imaging เข้าได้กับ pancreatitis"],
      supporting: ["ประเมินภาวะแทรกซ้อน organ failure/shock/ARF"],
      avoidIf: ["lab/imaging ยังไม่สอดคล้องเพียงพอ"],
    },
  },
  {
    slug: "influenza",
    name: "Influenza",
    aliases: ["influenza", "flu", "ไข้หวัดใหญ่"],
    diagnosisToWrite: ["Influenza", "Influenza with pneumonia"],
    thinkWhen: ["ไข้ ปวดเมื่อย ไอ และมีผลตรวจ influenza สนับสนุน", "หากไม่มีผลยืนยันไวรัส ให้ใช้กลุ่ม virus not identified ตามบริบทคลินิก"],
    considerMore: ["ถ้ามี pneumonia ร่วม ให้ระบุ influenza with pneumonia", "หากมี hypoxemia รุนแรงให้ประเมิน ARF"],
    notYetDiagnosis: ["ไม่ลง influenza/influenza with pneumonia หากยังไม่มีข้อมูลสนับสนุนพอ"],
    investigations: ["Influenza test", "CXR เมื่อสงสัยปอดอักเสบ", "SpO2/ABG เมื่อ severe"],
    icd10: ["J10.1", "J11.1", "J12.9"],
    seeAlso: ["pneumonia", "acute-respiratory-failure", "sepsis-septic-shock"],
    refs: ["R1", "R2", "R4", "R5"],
    chartChecklist: {
      mustHave: ["อาการไข้ + URI/myalgia เข้าได้ และมีข้อมูลสนับสนุน influenza"],
      supporting: ["ถ้ามี pneumonia ร่วมให้ระบุ influenza with pneumonia", "ประเมิน ARF/sepsis ในรายรุนแรง"],
      avoidIf: ["หลักฐานยังไม่พอแต่รีบลง influenza with pneumonia"],
    },
  },
  {
    slug: "covid-19-viral-pneumonia",
    name: "COVID-19 / Viral pneumonia",
    aliases: ["covid", "covid-19", "viral pneumonia", "ปอดอักเสบไวรัส"],
    diagnosisToWrite: ["COVID-19", "Viral pneumonia, unspecified (J12.9)", "COVID-19 with pneumonia"],
    thinkWhen: ["มีผลตรวจ COVID-19 สนับสนุน", "ถ้ามี pneumonia ร่วมให้ระบุชัดว่า COVID-19 with pneumonia"],
    considerMore: ["ถ้ามี hypoxemia หรือ respiratory support ให้พิจารณา ARF", "มองหา sepsis ในรายที่มีอาการรุนแรง"],
    notYetDiagnosis: ["ไม่ลง viral pneumonia หากยังไม่มี imaging/ข้อมูลสนับสนุนพอ"],
    investigations: ["COVID test", "CXR", "SpO2/ABG", "Inflammatory markers ตามบริบท"],
    icd10: ["U07.1", "J12.9", "J96.0"],
    seeAlso: ["pneumonia", "acute-respiratory-failure", "sepsis-septic-shock"],
    refs: ["R2", "R4", "R5"],
    chartChecklist: {
      mustHave: ["มีผลตรวจ COVID สนับสนุน", "หากมีปอดอักเสบร่วมให้ระบุ COVID-19 with pneumonia"],
      supporting: ["CXR/SpO2/ABG ช่วยแยกความรุนแรงและ ARF"],
      avoidIf: ["ยังไม่มี imaging/ข้อมูลพอ แต่สรุป viral pneumonia"],
    },
  },
  {
    slug: "ischemic-stroke",
    name: "Ischemic stroke",
    aliases: ["ischemic stroke", "cerebral infarction", "stroke ischemic", "stroke"],
    diagnosisToWrite: ["Cerebral infarction (I63.9)"],
    thinkWhen: ["CT/MRI ยืนยัน infarction"],
    considerMore: ["หากมี dysphagia/aspiration risk ให้พิจารณา aspiration pneumonia", "ประเมินภาวะโภชนาการเมื่อกินไม่ได้/นอนนาน"],
    notYetDiagnosis: ["ไม่ลง cerebral infarction หากยังไม่มีข้อมูลยืนยันทางภาพหรือ clinical สนับสนุนพอ"],
    investigations: ["CT/MRI brain", "Neurologic exam", "Swallowing assessment"],
    icd10: ["I63.9"],
    seeAlso: ["old-cva-hemiplegia", "pneumonia", "malnutrition"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["CT/MRI ยืนยัน infarction"],
      supporting: ["ประเมิน dysphagia/aspiration risk และภาวะโภชนาการร่วม"],
      avoidIf: ["ยังไม่มีข้อมูลยืนยันทางภาพเพียงพอ"],
    },
  },
  {
    slug: "hemorrhagic-stroke",
    name: "Hemorrhagic stroke",
    aliases: ["hemorrhagic stroke", "cerebral hemorrhage", "เลือดออกในสมอง"],
    diagnosisToWrite: ["Cerebral hemorrhage (I61.9)"],
    thinkWhen: ["CT brain ยืนยัน hemorrhage"],
    considerMore: ["แยก old CVA/hemiplegia หากมี neurologic deficit ค้างเดิมร่วม"],
    notYetDiagnosis: ["ไม่ลง hemorrhagic stroke หากยังไม่มีข้อมูลยืนยันทางภาพ"],
    investigations: ["CT brain", "Neurologic monitoring", "BP control context"],
    icd10: ["I61.9"],
    seeAlso: ["old-cva-hemiplegia", "seizure"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["CT brain ยืนยัน hemorrhage"],
      supporting: ["ติดตาม neurologic status และความดันโลหิต"],
      avoidIf: ["ยังไม่มีข้อมูลยืนยันทางภาพ"],
    },
  },
  {
    slug: "old-cva-hemiplegia",
    name: "Old CVA / Hemiplegia",
    aliases: ["old cva", "hemiplegia", "sequelae stroke", "อัมพาตครึ่งซีก"],
    diagnosisToWrite: ["Sequelae of cerebrovascular disease (I69.3/I69.4)", "Hemiplegia (G81.9)"],
    thinkWhen: ["มีประวัติ stroke เดิม และยังมี neurologic deficit", "หากไม่มี neuro deficit คงค้างชัด อาจไม่เข้าเกณฑ์ hemiplegia/sequelae"],
    considerMore: ["แยกโรคเฉียบพลันรอบใหม่ออกจาก sequelae เดิมให้ชัด"],
    notYetDiagnosis: ["ไม่ลง sequelae หากยังไม่มีประวัติ stroke เดิมที่ชัดเจน"],
    investigations: ["Neurologic exam", "ประวัติ prior stroke", "Functional assessment"],
    icd10: ["I69.3", "I69.4", "G81.9"],
    seeAlso: ["ischemic-stroke", "pneumonia"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีประวัติ stroke เดิม + neurologic deficit คงค้าง"],
      supporting: ["แยก episode ใหม่ออกจาก sequelae เดิมให้ชัด"],
      avoidIf: ["ไม่มีหลักฐาน deficit คงค้างแต่ลง sequelae/hemiplegia"],
    },
  },
  {
    slug: "seizure",
    name: "Seizure",
    aliases: ["seizure", "convulsion", "ชัก"],
    diagnosisToWrite: ["Seizure / convulsion ตามบริบท"],
    thinkWhen: ["มีอาการชักและข้อมูลทางคลินิกสอดคล้อง"],
    considerMore: ["ค้นหาสาเหตุร่วม เช่น hypoglycemia, hyponatremia, CNS infection"],
    notYetDiagnosis: ["ไม่สรุปสาเหตุจำเพาะของ seizure หากยังไม่มีข้อมูลพอ"],
    investigations: ["Glucose", "Electrolytes", "Neuroimaging ตามข้อบ่งชี้", "CSF เมื่อสงสัยติดเชื้อ CNS"],
    icd10: ["R56.8", "G40.9"],
    seeAlso: ["dka-hhs", "hyponatremia", "meningitis-encephalitis"],
    refs: ["R2", "R4"],
    chartChecklist: {
      mustHave: ["มีอาการชักและ clinical context สอดคล้อง"],
      supporting: ["ค้นหาสาเหตุร่วมด้วย glucose/electrolyte/neuroimaging/CSF ตามข้อบ่งชี้"],
      avoidIf: ["รีบสรุปสาเหตุจำเพาะทั้งที่ข้อมูลยังไม่พอ"],
    },
  },
  {
    slug: "meningitis-encephalitis",
    name: "Meningitis / Encephalitis",
    aliases: ["meningitis", "encephalitis", "เยื่อหุ้มสมองอักเสบ", "สมองอักเสบ"],
    diagnosisToWrite: ["Meningitis", "Encephalitis", "Cryptococcal meningitis (เมื่อเข้าได้)"],
    thinkWhen: ["ไข้ ปวดศีรษะ คอแข็ง หรือ altered mental status และมี CSF/lab สนับสนุน"],
    considerMore: ["ถ้ามีเชื้อจำเพาะ (เช่น crypto) ให้ลงตามเชื้อ", "อย่าลืม procedure เช่น lumbar puncture"],
    notYetDiagnosis: ["ไม่ลง meningitis/encephalitis หากยังไม่มีข้อมูลสนับสนุนทางคลินิก/CSF เพียงพอ"],
    investigations: ["CSF study", "Neuroimaging ตามข้อบ่งชี้", "Microbiology/antigen tests"],
    icd10: ["G00.9", "G03.9", "G04.9", "B45.1"],
    seeAlso: ["hiv-infection-disease", "sepsis-septic-shock", "lumbar-puncture-procedure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["ไข้/neurologic symptoms เข้าได้ + CSF/lab สนับสนุน"],
      supporting: ["ถ้ามีเชื้อจำเพาะให้ลงตามเชื้อ", "สรุป lumbar puncture เมื่อมีการทำจริง"],
      avoidIf: ["ข้อมูลทางคลินิกหรือ CSF ยังไม่พอแต่รีบลงวินิจฉัย"],
    },
  },
  {
    slug: "hiv-infection-disease",
    name: "HIV infection / disease",
    aliases: ["hiv", "hiv infection", "aids", "โรคติดเชื้อเอชไอวี"],
    diagnosisToWrite: [
      "Laboratory evidence of human immunodeficiency virus [HIV] (R75) - anti-HIV +ve แต่ยังไม่ได้ confirm ตามนิยามในเวชระเบียน",
      "Acute HIV infection syndrome (B23.0) - อาการเฉียบพลัน early HIV; anti-HIV อาจ -ve แต่ p24 Ag +ve ตามบริบท",
      "HIV disease resulting in infectious and parasitic diseases (B20) - ติดเชื้อ/ปรสิตที่เกี่ยวกับ HIV (มักเป็น Pdx เมื่อเป็นเหตุรับไว้หลัก)",
      "HIV disease resulting in malignant neoplasm (B21) - เช่น lymphoma/Kaposi ตามหลักฐาน",
      "HIV disease resulting in other specified diseases (B22) - เช่น CD4 เคย <350 + ภาวะที่ระบุใน B22",
      "HIV disease resulting in other conditions (B23.-) - ภาวะอื่นที่จัดใน B23 ตามรายละเอียดย่อย",
      "Unspecified human immunodeficiency virus [HIV] disease (B24) - โรคไม่เกี่ยวกลไก HIV โดยตรงแต่ยังอยู่ในกลุ่ม HIV disease — ใน CODING AUDIT 2562 มักบันทึกเป็น Sdx เมื่อมีโรคหลักอื่น",
      "Asymptomatic human immunodeficiency virus [HIV] infection status (Z21) - anti-HIV +ve ไม่มีอาการ/CD4 ปกติตามบันทึก — ใน CODING AUDIT มักเป็น Sdx",
    ],
    thinkWhen: [
      "มีผลตรวจยืนยัน HIV หรือมีการวินิจฉัยจากแพทย์ในเวชระเบียนชัดเจน",
      "ถ้ามี TB ปอด/เยื่อหุ้มสมองวัณโรค ฯลฯ ให้ลงโรคนั้นร่วมและพิจารณา B20 เมื่อเข้าเกณฑ์ ไม่แทนที่ด้วย Z21",
      "ถ้าโรคแทรกซ้อนไม่มีรหัสใน B20-B23 ให้ใช้รหัสโรคแทรกนั้นเป็น Pdx และบันทึก HIV disease เป็น Sdx (ตามหลักใน CODING AUDIT 2562)",
    ],
    considerMore: [
      "ถ้ามี opportunistic infection ให้ลงโรคติดเชื้อร่วมตามหลักฐาน (เช่น pulmonary tuberculosis, cryptococcal meningitis)",
      "แยก Z21 (asymptomatic) ออกจาก B20-B24 ตามคำวินิจฉัยและหลักฐาน — อย่าสลับเพราะสะดวก",
      "ผู้ป่วย HIV เสี่ยงวัณโรค: พิจารณา screening/culture และวินิจฉัยวัณโรคปอดเมื่อบริบทเข้าได้",
      "ภาวะ IRIS หลังเริ่ม ARV: ลงตามวินิจฉัยแพทย์และรหัสที่บันทึกในเวชระเบียน คู่กับ HIV code ตามบริบท",
    ],
    notYetDiagnosis: [
      "ไม่ลง HIV/AIDS หากยังไม่มีหลักฐานยืนยันหรือเอกสารวินิจฉัยชัดเจน",
      "ไม่ใช้ B24 แทนรหัส B20-B23 เมื่อมีหลักฐานจัดกลุ่มได้ชัด",
    ],
    investigations: ["HIV serology/confirmatory test", "CD4/viral load ตามบริบท", "ผลตรวจ OI ตามอาการ"],
    icd10: ["R75", "B23.0", "B20", "B21", "B22", "B23.8", "B24", "Z21"],
    seeAlso: ["meningitis-encephalitis", "sepsis-septic-shock", "pulmonary-tuberculosis"],
    refs: ["R1", "R2", "R4", "R5", "R6", "R7", "R8"],
    chartChecklist: {
      mustHave: ["มีผลตรวจยืนยัน HIV หรือแพทย์ระบุ diagnosis ชัดเจน"],
      supporting: ["มีข้อมูล OI/CD4/viral load สนับสนุนระดับความรุนแรง", "มี TB/OI จำเพาะให้ลงร่วมตามหลักฐาน"],
      avoidIf: [
        "ใช้คำว่า AIDS/HIV โดยไม่มีหลักฐานยืนยันในเวชระเบียน",
        "ลง Z21 ทั้งที่มี OI ชัดตามเกณฑ์ B20",
        "ลง B24 ทั้งที่ควรแยก B20-B23 ตามหลักฐาน",
      ],
    },
  },
  {
    slug: "pulmonary-tuberculosis",
    name: "Pulmonary tuberculosis",
    aliases: ["tuberculosis", "tb", "tb lung", "วัณโรคปอด", "ปอดวัณโรค", "ptb"],
    diagnosisToWrite: [
      "Tuberculosis of lung, confirmed by sputum with or without culture (A15.0) - AFB/PCR/GeneXpert ตามหลักฐาน (สอดคล้อง CODING AUDIT 2562)",
      "Tuberculosis of lung, confirmed by culture only (A15.1)",
      "Tuberculosis of lung, confirmed histologically (A15.2)",
      "Tuberculosis of lung, bacteriologically and histologically negative (A16.0) - วินิจฉัยคลินิก/รังสีโดยยังไม่เข้าเกณฑ์ A15",
      "Primary respiratory tuberculosis (A15.7 / A16.7) - ตามนิยามย่อยใน ICD-10 เมื่อบันทึกเป็น primary respiratory TB",
      "Other respiratory tuberculosis (A15.8 / A16.8)",
      "Acute miliary tuberculosis of a single specified site (A19.0) หรือ of multiple sites (A19.1) - พิจารณาเมื่อมีภาพ/บริบท acute miliary ชัด",
      "Miliary tuberculosis, unspecified (A19.9) - disseminated/generalized เมื่อยังไม่จำเพาะย่อย",
    ],
    thinkWhen: [
      "ไอเรื้อรัง/เสมหะ/ซีด/น้ำหนักลด + CXR/CT สงสัย PTB หรือมีการวินิจฉัยจากแพทย์",
      "ผู้ป่วย HIV หรือภาวะภูมิคุ้มกันต่ำ — พิจารณา PTB และการลง B20 ร่วมเมื่อเข้าเกณฑ์",
    ],
    considerMore: [
      "แยก principal vs secondary ตามเหตุรับไว้และ clinical course (R1/R5/R6)",
      "ถ้ามี TB meningitis (A17.0) หรือ sepsis ให้ลงร่วมตามหลักฐาน",
      "สรุปยาต้านวัณโรค/ระยะรักษาเมื่อมีในเวชระเบียน",
    ],
    notYetDiagnosis: ["ไม่ลง PTB หากยังไม่มีหลักฐานรังสี/ห้องปฏิบัติการ/คำวินิจฉัยแพทย์สนับสนุนเพียงพอ"],
    investigations: ["Sputum AFB/culture/GeneXpert", "CXR/CT chest", "HIV status ตามบริบท", "ประเมิน disseminated/CNS"],
    icd10: ["A15.0", "A15.1", "A15.2", "A15.7", "A15.8", "A16.0", "A16.7", "A16.8", "A17.0", "A19.0", "A19.1", "A19.9"],
    seeAlso: ["hiv-infection-disease", "pneumonia", "meningitis-encephalitis", "sepsis-septic-shock"],
    refs: ["R1", "R2", "R4", "R5", "R6", "R7", "R8"],
    chartChecklist: {
      mustHave: ["มีหลักฐานวินิจฉัย PTB หรือยืนยัน/รักษาตามแนวทางที่สอดคล้องเวชระเบียน"],
      supporting: ["ผลเชื้อ/รังสีสนับสนุน A15.0 vs A16.0", "ผู้ป่วย HIV — ตรวจสอบการลง B20 และโรคร่วม"],
      avoidIf: ["สงสัยจาก CXR อย่างเดียวโดยไม่มีแพทย์วินิจฉัยหรือข้อมูลติดตาม"],
    },
  },
  {
    slug: "postpartum-hemorrhage",
    name: "Postpartum hemorrhage",
    aliases: ["pph", "postpartum hemorrhage", "ตกเลือดหลังคลอด"],
    diagnosisToWrite: ["Postpartum hemorrhage (O72.1)", "Delayed and secondary postpartum hemorrhage (O72.2)", "Obstetric shock (O75.1)"],
    thinkWhen: [
      "ระหว่างคลอดมี blood loss สูงตามเกณฑ์และแพทย์วินิจฉัย (แนวทางที่ใช้บ่อย: NL > 500 mL หรือ C/S > 1000 mL)",
      "ภายใน < 6 สัปดาห์หลังคลอดมีซีด/ความดันต่ำและแพทย์วินิจฉัย",
    ],
    considerMore: ["ถ้ามี shock ให้เพิ่ม obstetric shock", "ถ้ามีเสียเลือดมากและให้เลือด พิจารณา D62 ตามบริบท", "ต้องมี blood loss documentation และการรักษาสอดคล้อง"],
    notYetDiagnosis: ["ไม่ลง PPH/obstetric shock หากยังไม่มีข้อมูลสนับสนุนเพียงพอ"],
    investigations: ["Blood loss documentation", "Vital signs", "CBC trend", "Transfusion record"],
    icd10: ["O72.1", "O72.2", "O75.1", "D62"],
    seeAlso: ["blood-transfusion-procedure", "hypovolemic-shock", "gi-bleeding"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มี blood loss ตามเกณฑ์และแพทย์วินิจฉัย", "แยก immediate PPH กับ delayed PPH ให้ชัด"],
      supporting: ["มี shock ให้เพิ่ม O75.1", "มี transfusion/ซีดจากเสียเลือด ให้พิจารณา D62 และ procedure"],
      avoidIf: ["ยังไม่มี blood loss documentation หรือ clinical support เพียงพอ"],
    },
  },
  {
    slug: "newborn-jaundice",
    name: "Newborn jaundice",
    aliases: ["newborn jaundice", "neonatal jaundice", "ตัวเหลืองทารก"],
    diagnosisToWrite: [
      "Neonatal jaundice due to other specified excessive haemolysis (P58.8)",
      "ABO isoimmunization of fetus and newborn (P55.1)",
      "Minor blood group incompatibility (P55.8)",
      "Neonatal jaundice from breast milk inhibitor (P59.3)",
      "Neonatal jaundice from other specified causes (P59.8)",
      "Neonatal jaundice, unspecified (P59.9)",
    ],
    thinkWhen: [
      "ทารกตัวเหลืองและมีข้อมูล bilirubin/สาเหตุสนับสนุนตามบริบทเวลาและ clinical course",
      "เกณฑ์ที่ใช้บ่อย: term bilirubin > 12 mg/dL หรือ preterm > 15 mg/dL ร่วม clinical context",
      "Breast milk jaundice (P59.3): ตัวเหลืองหลังคลอด > 5 วัน และไม่พบสาเหตุอื่น",
      "Breastfeeding jaundice/hypocaloric jaundice (P59.8): มักเกิดช่วง 2-3 วันแรกและมีบริบทกินนมน้อย",
    ],
    considerMore: ["หากได้ phototherapy อย่าลืมสรุปหัตถการ", "ถ้าเป็น preterm/LBW ให้ประเมินร่วมกัน", "ถ้าสงสัย G6PD/ABO/minor blood group ต้องมีข้อมูลสาเหตุสนับสนุนก่อนลงรหัสจำเพาะ"],
    notYetDiagnosis: ["ไม่สรุปสาเหตุจำเพาะ (เช่น breast milk, ABO, G6PD) หากยังไม่มีข้อมูลสนับสนุนชัดเจน"],
    investigations: ["Total bilirubin trend", "Hemolysis workup ตามบริบท", "Clinical timing and feeding history"],
    icd10: ["P58.8", "P55.1", "P55.8", "P59.3", "P59.8", "P59.9"],
    seeAlso: ["preterm-low-birth-weight", "neonatal-sepsis"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มี neonatal jaundice พร้อม bilirubin/clinical timing สนับสนุน"],
      supporting: ["แยกสาเหตุ (ABO/G6PD/breast milk/breastfeeding) ตามข้อมูลจริง", "มี phototherapy/transfusion ให้สรุปหัตถการ"],
      avoidIf: ["ยังไม่ตัดสาเหตุอื่น แต่ลงรหัสสาเหตุจำเพาะทันที"],
    },
  },
  {
    slug: "neonatal-sepsis",
    name: "Neonatal sepsis",
    aliases: ["neonatal sepsis", "sepsis newborn", "ติดเชื้อในทารกแรกเกิด"],
    diagnosisToWrite: ["Sepsis of newborn", "Environmental hyperthermia of newborn (P81.0)", "Other prophylactic chemotherapy (Z29.2)"],
    thinkWhen: [
      "ทารกแรกเกิดมีข้อมูลเข้าได้กับ sepsis และได้รับ IV antibiotics ตามแนวทาง",
      "โดยทั่วไปควรมีอาการเข้าได้หลายระบบ + ผล lab สนับสนุน และได้ antibiotics >= 5 วัน (ยกเว้นเสียชีวิต/refer)",
    ],
    considerMore: ["ในทารกเสี่ยงติดเชื้อสูงที่ให้ prophylaxis ให้ลง Z29.2 ตามบริบท", "แยกภาวะจากสิ่งแวดล้อม (P81.0) เมื่อตรงเกณฑ์", "ควรมี blood culture/การติดตามการรักษารองรับ"],
    notYetDiagnosis: ["ไม่ลง neonatal sepsis หากยังไม่มีข้อมูลสนับสนุนและการรักษาตามเกณฑ์"],
    investigations: ["Sepsis workup newborn", "Blood culture", "Antibiotic course documentation"],
    icd10: ["P36.9", "P81.0", "Z29.2"],
    seeAlso: ["sepsis-septic-shock", "newborn-jaundice", "preterm-low-birth-weight"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีอาการและ lab สนับสนุน neonatal sepsis + การรักษาสอดคล้อง"],
      supporting: ["โดยทั่วไปมี IV antibiotics >= 5 วัน (ยกเว้น refer/death)", "ราย prophylaxis ให้ใช้ Z29.2 ตามบริบท"],
      avoidIf: ["ยังไม่มีข้อมูลสนับสนุนและการรักษาตามเกณฑ์"],
    },
  },
  {
    slug: "preterm-low-birth-weight",
    name: "Preterm / Low birth weight",
    aliases: ["preterm", "low birth weight", "lbw", "คลอดก่อนกำหนด"],
    diagnosisToWrite: [
      "Extremely low birth weight (P07.0)",
      "Other low birth weight (P07.1)",
      "Other preterm infant (P07.3)",
      "Singleton, born in hospital (Z38.0)",
    ],
    thinkWhen: [
      "ใช้ข้อมูล GA, BW และบริบททางคลินิกเพื่อเลือกรหัสที่ตรงที่สุด",
      "P07.0: BW < 1000 g และ GA < 37 สัปดาห์",
      "P07.1: BW 1000-2499 g และ GA < 37 สัปดาห์",
      "P07.3: BW > 2500 g แต่ GA < 37 สัปดาห์ และมีข้อมูลสนับสนุน preterm",
    ],
    considerMore: ["มองหาภาวะแทรกซ้อนร่วม เช่น jaundice, sepsis, respiratory distress"],
    notYetDiagnosis: ["ไม่ลงรหัสจำเพาะเกินข้อมูล หากยังไม่มีหลักฐาน GA/BW/clinical criteria รองรับ"],
    investigations: ["Gestational age", "Birth weight", "Neonatal clinical assessment"],
    icd10: ["P07.0", "P07.1", "P07.3", "Z38.0"],
    seeAlso: ["newborn-jaundice", "neonatal-sepsis"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีข้อมูล GA + BW ชัดเพื่อเลือกรหัส preterm/LBW"],
      supporting: ["มองหาภาวะแทรกซ้อนร่วม เช่น jaundice/sepsis/RDS"],
      avoidIf: ["ข้อมูล GA/BW ไม่พอ แต่ลงรหัสจำเพาะเกินข้อมูล"],
    },
  },
  {
    slug: "uti-acute-pyelonephritis",
    name: "UTI / Acute pyelonephritis",
    aliases: ["uti", "acute pyelonephritis", "acute cystitis", "ปัสสาวะติดเชื้อ"],
    diagnosisToWrite: [
      "Urinary tract infection (N39.0) - ใช้เมื่อเป็น UTI แต่ยังไม่ระบุตำแหน่งได้ชัด",
      "Acute cystitis (N30.0) - ใช้เมื่ออาการเด่นเป็น lower UTI/cystitis",
      "Acute pyelonephritis (N10) - ใช้เมื่อมีไข้หรือ flank pain และเข้าได้กับ upper UTI",
    ],
    thinkWhen: [
      "มี dysuria/urgency/frequency หรือ flank pain + ไข้ และมีข้อมูล UA/culture สนับสนุน",
      "Pyelonephritis: มักมีไข้สูง + CVA tenderness ร่วมกับหลักฐาน UTI",
      "Cystitis: อาการ lower urinary tract เด่น โดยยังไม่มีหลักฐาน upper tract",
    ],
    considerMore: ["ถ้ามี systemic involvement และ source ชัด อาจใช้ pyelonephritis เป็น principal", "ประเมิน sepsis/AKI ร่วมในรายรุนแรง"],
    notYetDiagnosis: ["ไม่ลง pyelonephritis หากยังไม่มีข้อมูล upper UTI สนับสนุน", "ไม่สรุปจาก UA ผิดปกติอย่างเดียวโดยไม่มี clinical context"],
    investigations: ["Urinalysis", "Urine culture", "CBC", "Renal function", "Imaging เมื่อสงสัย complicated UTI"],
    icd10: ["N39.0", "N10", "N30.0"],
    seeAlso: ["sepsis-septic-shock", "aki-acute-renal-failure"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["อาการทางเดินปัสสาวะ + UA/culture สนับสนุน", "แยก lower vs upper UTI ให้ชัด"],
      supporting: ["pyelonephritis มักมีไข้สูง + CVA tenderness", "ประเมิน sepsis/AKI ในรายรุนแรง"],
      avoidIf: ["สรุป pyelonephritis จาก UA ผิดปกติอย่างเดียว"],
    },
  },
  {
    slug: "malaria",
    name: "Malaria",
    aliases: ["malaria", "falciparum", "vivax", "ไข้มาลาเรีย"],
    diagnosisToWrite: ["Malaria", "Falciparum malaria", "Vivax malaria", "Severe malaria"],
    thinkWhen: ["มีไข้เป็นๆหายๆ หรือประวัติเสี่ยง และมีผลตรวจยืนยันเชื้อ"],
    considerMore: ["ถ้าทราบชนิดเชื้อให้ลง diagnosis จำเพาะ", "มี organ failure/shock/AKI/anemia/hypoglycemia ให้พิจารณา severe malaria"],
    notYetDiagnosis: ["ไม่ลง malaria หากยังไม่มีผลยืนยันหรือข้อมูลสนับสนุนพอ", "ไม่ใช้คำกว้างเมื่อทราบชนิดเชื้อแล้ว"],
    investigations: ["Malaria smear/rapid test", "CBC", "Renal function", "Glucose", "Lactate/organ dysfunction assessment"],
    icd10: ["B50.9", "B51.9", "B52.9", "B54"],
    seeAlso: ["sepsis-septic-shock", "aki-acute-renal-failure", "hypoglycemia"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีผลตรวจยืนยันเชื้อมาลาเรีย"],
      supporting: ["ระบุชนิดเชื้อเมื่อทราบ", "มี organ dysfunction/shock/AKI/anemia/hypoglycemia ให้พิจารณา severe malaria"],
      avoidIf: ["ยังไม่มีผลยืนยันเชื้อแต่สรุปมาลาเรียจำเพาะ"],
    },
  },
  {
    slug: "melioidosis",
    name: "Melioidosis",
    aliases: ["melioidosis", "b. pseudomallei", "เมลิออยโดสิส"],
    diagnosisToWrite: ["Melioidosis", "Melioidosis with sepsis", "Pneumonia due to melioidosis", "Abscess due to melioidosis"],
    thinkWhen: ["มีผลเพาะเชื้อหรือข้อมูลยืนยัน Burkholderia pseudomallei"],
    considerMore: ["ถ้าทราบ source ชัด (pneumonia/liver abscess/splenic abscess) ให้ใช้ source เป็น principal แล้วเพิ่ม melioidosis/sepsis"],
    notYetDiagnosis: ["ไม่ลง melioidosis หากยังไม่มีหลักฐานยืนยันพอ", "ไม่ลง sepsis กว้างๆ หาก source ชัดและควรระบุได้"],
    investigations: ["Blood/sputum/pus culture", "Imaging เพื่อหา abscess/source", "Organ dysfunction assessment"],
    icd10: ["A24.9", "A41.9"],
    seeAlso: ["sepsis-septic-shock", "pneumonia", "acute-pancreatitis"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีผลเพาะเชื้อ/หลักฐานยืนยัน Burkholderia pseudomallei"],
      supporting: ["ถ้าทราบ source ชัด ใช้ source เป็น principal แล้วเพิ่ม melioidosis/sepsis"],
      avoidIf: ["ยังไม่มีหลักฐานยืนยัน แต่ลง melioidosis จำเพาะ"],
    },
  },
  {
    slug: "leptospirosis",
    name: "Leptospirosis",
    aliases: ["leptospirosis", "lepto", "โรคฉี่หนู"],
    diagnosisToWrite: ["Leptospirosis (A27.9)", "Severe leptospirosis"],
    thinkWhen: ["ไข้เฉียบพลัน + อาการเข้าได้ + ประวัติเสี่ยงสัมผัสน้ำ/ดิน/สัตว์ และมีผลตรวจสนับสนุน"],
    considerMore: ["ถ้ามีไตวาย ดีซ่าน เลือดออก หายใจล้มเหลว หรือ shock ให้พิจารณา severe leptospirosis"],
    notYetDiagnosis: ["ไม่ลง leptospirosis หากยังไม่มีข้อมูลเสี่ยงหรือผลตรวจสนับสนุนพอ"],
    investigations: ["Serology/PCR ตามที่มี", "CBC", "Renal/liver function", "CXR/ABG เมื่อสงสัยรุนแรง"],
    icd10: ["A27.9"],
    seeAlso: ["aki-acute-renal-failure", "sepsis-septic-shock", "acute-respiratory-failure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีอาการเข้าได้ + ประวัติเสี่ยงสัมผัส + ผลตรวจสนับสนุน"],
      supporting: ["มี organ failure/shock ให้พิจารณา severe leptospirosis"],
      avoidIf: ["ยังไม่มีข้อมูลเสี่ยงหรือผลตรวจสนับสนุนพอ"],
    },
  },
  {
    slug: "scrub-typhus",
    name: "Scrub typhus",
    aliases: ["scrub typhus", "rickettsial infection", "สครับไทฟัส"],
    diagnosisToWrite: ["Scrub typhus", "Scrub typhus with sepsis"],
    thinkWhen: ["ไข้ + ประวัติเสี่ยงพื้นที่หญ้า/ป่า/ไร่ + eschar/ผื่น/ต่อมน้ำเหลือง หรือผลตรวจสนับสนุน"],
    considerMore: ["ถ้ามี organ dysfunction หรือภาพรวมรุนแรง ให้เพิ่ม sepsis ตามเกณฑ์"],
    notYetDiagnosis: ["ไม่ลง scrub typhus หากยังไม่มีข้อมูลเสี่ยงหรือผลตรวจสนับสนุนเพียงพอ"],
    investigations: ["Serology/PCR ตามที่มี", "CBC/LFT", "Organ dysfunction assessment"],
    icd10: ["A75.3"],
    seeAlso: ["sepsis-septic-shock", "acute-respiratory-failure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีไข้ + ประวัติเสี่ยง + eschar/ผลตรวจสนับสนุน"],
      supporting: ["มี organ dysfunction ให้พิจารณา sepsis ร่วม"],
      avoidIf: ["ข้อมูลเสี่ยง/ผลตรวจยังไม่พอ"],
    },
  },
  {
    slug: "cellulitis-necrotizing-fasciitis",
    name: "Cellulitis / Necrotizing fasciitis",
    aliases: ["cellulitis", "necrotizing fasciitis", "nec fasc", "แผลติดเชื้อ"],
    diagnosisToWrite: [
      "Cellulitis, unspecified (L03.9)",
      "Local infection of skin and subcutaneous tissue, unspecified (L08.9)",
      "Necrotizing fasciitis (M72.6)",
      "Post traumatic wound infection (T79.3)",
    ],
    thinkWhen: [
      "ผิวหนังบวมแดงร้อนเจ็บเข้าได้กับ cellulitis",
      "มีข้อมูลสนับสนุนการติดเชื้อลุกลาม/เนื้อตายร่วมการรักษาเข้าได้กับ necrotizing fasciitis",
      "necrotizing fasciitis ควรมีหลักฐานรุนแรง เช่น hemorrhagic bleb/เนื้อตาย/operative finding และการรักษาแบบ excisional debridement",
    ],
    considerMore: ["กรณีแผลอุบัติเหตุที่ติดเชื้อให้ระบุ post-traumatic wound infection และ external cause", "ถ้ามี debridement/fasciotomy/amputation ให้สรุปหัตถการ"],
    notYetDiagnosis: ["ไม่ลง necrotizing fasciitis หากยังไม่มีหลักฐานทางคลินิก/operative เพียงพอ"],
    investigations: ["Clinical soft tissue assessment", "Culture", "Imaging ตามข้อบ่งชี้", "Operative findings"],
    icd10: ["L03.9", "L08.9", "M72.6", "T79.3"],
    seeAlso: ["sepsis-septic-shock", "debridement-procedure", "external-cause"],
    refs: ["R1", "R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐาน skin/soft tissue infection ตามโรคที่เลือก", "ถ้าสงสัย nec fasc ต้องมีหลักฐานความรุนแรงและการรักษารองรับ"],
      supporting: ["เชื่อมโยง external cause ในแผลอุบัติเหตุ", "สรุป debridement/fasciotomy/amputation เมื่อมีการทำจริง"],
      avoidIf: ["ยังไม่มีข้อมูลสนับสนุนพอ แต่ลง necrotizing fasciitis"],
    },
  },
  {
    slug: "blood-transfusion-procedure",
    name: "Blood transfusion (Procedure)",
    aliases: ["blood transfusion", "prc transfusion", "platelet transfusion", "ให้เลือด"],
    diagnosisToWrite: [
      "Whole blood transfusion (ICD-9-CM: 99.03)",
      "Packed red cell transfusion (ICD-9-CM: 99.04)",
      "Platelet transfusion (ICD-9-CM: 99.05)",
      "Transfusion of coagulation factors/FFP/Cryo (ICD-9-CM: 99.06)",
    ],
    thinkWhen: ["มีการให้เลือดจริงตามชนิด blood component", "ถ้ามีเพียงคำสั่งแต่ยังไม่ได้ให้จริง ยังไม่ควรลงหัตถการ transfusion"],
    considerMore: ["ถ้ามีแค่สั่งแต่ยังไม่ได้ให้จริง ยังไม่สรุป transfusion procedure"],
    notYetDiagnosis: ["ไม่ลงหัตถการหากไม่มีหลักฐานการให้จริง"],
    investigations: ["Transfusion record", "Blood component documentation"],
    icd10: ["Z51.3"],
    icd9: ["99.03", "99.04", "99.05", "99.06"],
    seeAlso: ["gi-bleeding", "postpartum-hemorrhage", "anemia"],
    refs: ["R1", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีการให้เลือดจริงและระบุชนิด component ชัด"],
      supporting: ["ลงรหัสหัตถการตาม component ที่ให้จริง"],
      avoidIf: ["มีแค่คำสั่งแต่ยังไม่ได้ให้จริง"],
    },
  },
  {
    slug: "dialysis-procedure",
    name: "Hemodialysis / Peritoneal dialysis (Procedure)",
    aliases: ["hemodialysis", "peritoneal dialysis", "capd", "hd", "pd"],
    diagnosisToWrite: [
      "Dialysis care status (ICD-10: Z49.1)",
      "Peritoneal dialysis care status (ICD-10: Z49.2)",
      "Dependence on renal dialysis (ICD-10: Z99.2)",
      "Hemodialysis procedure (ICD-9-CM: 39.95)",
      "Peritoneal dialysis procedure (ICD-9-CM: 54.98)",
    ],
    thinkWhen: ["มีสถานะการดูแลหรือหัตถการ dialysis จริงตามบริบท", "แยกสถานะการดูแล (Z49./Z99.2) ออกจากหัตถการจริง (54.93/54.95/54.98)"],
    considerMore: ["ระบุหัตถการเฉพาะ เช่น TK insertion/removal ตาม operative note"],
    notYetDiagnosis: ["ไม่ลงหัตถการล้างไตหากยังไม่มีบันทึกทำจริง"],
    investigations: ["Dialysis session documentation", "Procedure note", "Renal replacement plan"],
    icd10: ["Z49.1", "Z49.2", "Z99.2"],
    icd9: ["39.95", "54.93", "54.95", "54.98"],
    seeAlso: ["ckd-esrd", "aki-acute-renal-failure"],
    refs: ["R2", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มีหลักฐานสถานะ dialysis care หรือหัตถการจริงที่ทำ"],
      supporting: ["แยก Z-code (care status) และ procedure code ให้ถูกบริบท"],
      avoidIf: ["ยังไม่มีบันทึกทำจริงแต่ลงหัตถการ"],
    },
  },
  {
    slug: "debridement-procedure",
    name: "Debridement (Procedure)",
    aliases: ["debridement", "excisional debridement", "nonexcisional debridement"],
    diagnosisToWrite: [
      "Nonexcisional debridement (ICD-9-CM: 86.28)",
      "Excisional debridement (ICD-9-CM: 86.22)",
    ],
    thinkWhen: ["มีหลักฐานหัตถการ debridement ชัดจากบันทึกการรักษา/operative note"],
    considerMore: ["หากไม่มีข้อมูลพอว่า excisional ให้ใช้ nonexcisional", "ตำแหน่งที่มีรหัสเฉพาะ ควรใช้รหัสเฉพาะตำแหน่งนั้น", "หากระบุแค่ debridement โดยไม่มีรายละเอียดเนื้อตายที่ตัดออก ไม่ควรตีความเป็น excisional"],
    notYetDiagnosis: ["ไม่ลง excisional debridement หากยังไม่มีหลักฐานสนับสนุนชัดเจน"],
    investigations: ["Operative/procedure note", "Wound assessment documentation"],
    icd10: [],
    icd9: ["86.28", "86.22"],
    seeAlso: ["cellulitis-necrotizing-fasciitis", "external-cause"],
    refs: ["R1", "R4", "R6"],
    chartChecklist: {
      mustHave: ["มี procedure/operative note ยืนยันการทำ debridement"],
      supporting: ["ถ้าไม่มีหลักฐานตัดเนื้อตายชัด ให้ใช้ nonexcisional"],
      avoidIf: ["ตีความเป็น excisional โดยไม่มีหลักฐานเพียงพอ"],
    },
  },
  {
    slug: "lumbar-puncture-procedure",
    name: "Lumbar puncture (Procedure)",
    aliases: ["lumbar puncture", "lp", "เจาะน้ำไขสันหลัง"],
    diagnosisToWrite: ["Lumbar puncture (ICD-9-CM: 03.31)"],
    thinkWhen: ["มีการทำ LP จริงตามบันทึกหัตถการ"],
    considerMore: ["เชื่อมโยงกับ diagnosis ที่เกี่ยวข้อง เช่น meningitis/encephalitis/seizure workup"],
    notYetDiagnosis: ["ไม่ลงหัตถการหากไม่มีบันทึกทำจริง"],
    investigations: ["Procedure note", "CSF analysis record"],
    icd10: [],
    icd9: ["03.31"],
    seeAlso: ["meningitis-encephalitis", "seizure"],
    refs: ["R4", "R6"],
    chartChecklist: {
      mustHave: ["มีบันทึกทำ lumbar puncture จริง"],
      supporting: ["เชื่อมโยงกับ diagnosis ที่เป็นข้อบ่งชี้ในการทำหัตถการ"],
      avoidIf: ["ไม่มีบันทึกหัตถการ แต่ลง procedure"],
    },
  },
  {
    slug: "chest-tube-pleural-procedure",
    name: "Chest tube / Pleural procedure",
    aliases: ["chest tube", "thoracentesis", "pleural tapping", "ใส่ท่อทรวงอก"],
    diagnosisToWrite: [
      "Thoracentesis (ICD-9-CM: 34.91)",
      "Chest tube insertion (ICD-9-CM: 34.04)",
    ],
    thinkWhen: ["มีหัตถการ pleural intervention ทำจริงตามบริบทผู้ป่วย"],
    considerMore: ["ควรสรุปชนิดหัตถการให้ชัดเจนตามที่ทำจริง"],
    notYetDiagnosis: ["ไม่ลงหัตถการหากไม่มีหลักฐาน procedure documentation"],
    investigations: ["Procedure note", "Imaging before/after procedure"],
    icd10: [],
    icd9: ["34.91", "34.04"],
    seeAlso: ["pleural-effusion", "pneumonia"],
    refs: ["R4", "R6"],
    chartChecklist: {
      mustHave: ["มี procedure documentation ว่าทำ thoracentesis/chest tube จริง"],
      supporting: ["มี imaging ก่อน/หลังหัตถการช่วยยืนยันบริบท"],
      avoidIf: ["ยังไม่มีหลักฐานทำหัตถการจริง"],
    },
  },
  {
    slug: "external-cause",
    name: "External cause",
    aliases: ["external cause", "injury mechanism", "สาเหตุภายนอกการบาดเจ็บ"],
    diagnosisToWrite: ["กลไกการบาดเจ็บ", "สถานที่เกิดเหตุ", "กิจกรรมขณะเกิดเหตุ"],
    thinkWhen: ["ใน trauma case ควรระบุ external cause ให้ครบเท่าที่มีข้อมูล"],
    considerMore: ["ระบุร่วมกับ fracture/open wound/burn/head injury ตามบริบท"],
    notYetDiagnosis: ["ไม่เติม external cause เกินข้อมูลที่มีจริงในเวชระเบียน"],
    investigations: ["Injury narrative", "Accident context documentation"],
    icd10: ["V01-Y98"],
    seeAlso: ["cellulitis-necrotizing-fasciitis", "debridement-procedure"],
    refs: ["R2", "R6"],
    chartChecklist: {
      mustHave: ["กรณี trauma มีข้อมูลกลไก + สถานที่ + กิจกรรมเท่าที่มี"],
      supporting: ["เชื่อมโยงกับ injury diagnosis/หัตถการที่เกี่ยวข้อง"],
      avoidIf: ["เติม external cause เกินข้อมูลจริงในเวชระเบียน"],
    },
  },
];

/** Static catalog QA date (bump when you re-audit slugs/refs against guidelines). */
export const DISEASE_KNOWLEDGE_LAST_REVIEWED = "2026-04-27";

export type DiseaseCatalogAudit = {
  lastReviewed: string;
  total: number;
  withIssues: number;
  issues: { slug: string; issues: string[] }[];
};

/** Structural checks only — not a substitute for clinical guideline review. */
export function auditDiseaseCatalog(diseases: DiseaseSummary[]): DiseaseCatalogAudit {
  const refIds = new Set(KNOWLEDGE_REFERENCES.map((r) => r.id));
  const slugs = new Set(diseases.map((d) => d.slug));
  const issues: { slug: string; issues: string[] }[] = [];
  for (const d of diseases) {
    const row: string[] = [];
    if (!d.diagnosisToWrite?.length) row.push("missing diagnosisToWrite");
    if (!d.refs?.length) row.push("missing refs");
    for (const r of d.refs || []) {
      if (!refIds.has(r)) row.push(`unknown ref: ${r}`);
    }
    for (const s of d.seeAlso || []) {
      if (!slugs.has(s)) row.push(`seeAlso → invalid slug: ${s}`);
    }
    const hasIcd10 = (d.icd10?.length ?? 0) > 0;
    const hasIcd9 = (d.icd9?.length ?? 0) > 0;
    if (!hasIcd10 && !hasIcd9) row.push("missing icd10 and icd9");
    if (row.length) issues.push({ slug: d.slug, issues: row });
  }
  const maxIssues = 100;
  return {
    lastReviewed: DISEASE_KNOWLEDGE_LAST_REVIEWED,
    total: diseases.length,
    withIssues: issues.length,
    issues: issues.slice(0, maxIssues),
  };
}

